# –ü–ª–∞–Ω:
1. Python
2. Numpy<b>
3. Pandas</b>
4. Regexp + <b>regexp with dataframes</b>
5. Texts
6. Matplotlib, Seaborn
7. Classification, clustering, binary, multiclass, multilabel
8. Metrics
9. Feature extraction
10. Pyspark/sql

<img src="gifs/pandas.gif" width="400">

* Pandas –≤ –∫–∞—Ä—Ç–∏–Ω–∫–∞—Ö

https://jalammar.github.io/gentle-visual-intro-to-data-analysis-python-pandas/

* 10 minutes to pandas

https://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html

* üêº—Ä–µ–∞–ª—å–Ω–æ –∫–ª–∞—Å—Å–Ω—ã–π —Ç–≤–∏—Ç—Ç–µ—Ä —á—É–≤–∞–∫–∞ —Å –∫—Ä—É—Ç—ã–º–∏ pandas tricks:
    
https://mobile.twitter.com/i/moments/1158828895547854849

In [2]:
import numpy as np
import pandas as pd

1. –ö–∞–∫ —Å–æ–∑–¥–∞—Ç—å pd.Series –∏–∑ –ª–∏—Å—Ç–∞, numpy array –∏ —Å–ª–æ–≤–∞—Ä—è(dict)? (‚òÖ‚òÜ‚òÜ)

In [772]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

mylist = pd.Series(mylist)
myarr = pd.Series(myarr)
mydict = pd.Series(mydict)
print(type(mylist))
print(mylist,'\n')
print(type(myarr))
print(myarr,'\n')
print(type(mydict))
print(mydict)

<class 'pandas.core.series.Series'>
0     a
1     b
2     c
3     e
4     d
     ..
21    v
22    w
23    x
24    y
25    z
Length: 26, dtype: object

<class 'pandas.core.series.Series'>
0      0
1      1
2      2
3      3
4      4
      ..
21    21
22    22
23    23
24    24
25    25
Length: 26, dtype: int64

<class 'pandas.core.series.Series'>
a     0
b     1
c     2
e     3
d     4
     ..
v    21
w    22
x    23
y    24
z    25
Length: 26, dtype: int64

2. –ö–∞–∫ —Å–¥–µ–ª–∞—Ç—å –ø—Ä–µ–≤—Ä–∞—Ç–∏—Ç—å –∏–Ω–¥–µ–∫—Å—ã –∏–∑ –¥–∞—Ç–∞—Ñ—Ä–µ–π–º–∞ –≤ –∫–æ–ª–æ–Ω–∫—É? (‚òÖ‚òÜ‚òÜ)

In [4]:
df=pd.DataFrame(['a', 'b', 'c'])

# df['index'] = df.index
# or 
df.insert(0, 'index', df.index, True)
print(df)

   0
0  a
1  b
2  c

In [5]:
df.reset_index()

   index  0
0      0  a
1      1  b
2      2  c

3. –ö–∞–∫ –∏–∑ –Ω–µ—Å–∫–æ–ª—å–∫–∏—Ö pd.Series —Å–¥–µ–ª–∞—Ç—å –æ–¥–∏–Ω –¥–∞—Ç–∞—Ñ—Ä–µ–π–º? (‚òÖ‚òÖ‚òÜ)

(hint: pd.concat –∏–ª–∏ —Å–ª–æ–≤–∞—Ä—å —Å –∫–æ–ª–æ–Ω–∫–∞–º–∏)

In [16]:
df1=pd.Series(['a', 'b', 'c'])
df2=pd.Series(['aa', 'b1', 'c2'])
df3=pd.Series(['44', '55', '66'])
pd.concat([df1,df2,df3], ignore_index = True)

0     a
1     b
2     c
3    aa
4    b1
5    c2
6    44
7    55
8    66
dtype: object

4. –ö–∞–∫ –ø–æ–ª—É—á–∏—Ç—å —Å—Ç—Ä–æ–∫–∏ –∏–∑ series A, –∫–æ—Ç–æ—Ä—ã–µ –Ω–µ —Å–æ–¥–µ—Ä–∂–∞—Ç—Å—è –≤ series B? (‚òÖ‚òÖ‚òÜ)

In [7]:
df1=pd.Series(['a', 'b', 'c'])
df2=pd.Series(['a', 'b1', 'c2'])

for i in range(len(df1)):
        if df1.eq(df2, axis=0)[i] == False:
            print(df1[i])

b
c

In [9]:
df1[~df2.isin(df1)]

1    b
2    c
dtype: object

5. –ö–∞–∫ –ø–æ–ª—É—á–∏—Ç—å –∏–∑ series/dataframe –º–∏–Ω–∏–º—É–º, 25–π –ø–µ—Ä—Å–µ–Ω—Ç–∏–ª—å, –º–µ–¥–∏–∞–Ω—É, 75—Ç—ã–π –ø–µ—Ä—Å–µ–Ω—Ç–∏–ª—å, –º–∞–∫—Å–∏–º—É–º? (‚òÖ‚òÜ‚òÜ)

(hint: –∏—Å–ø–æ–ª—å–∑–æ–≤–∞—Ç—å –æ–¥–Ω—É –∫–æ–º–∞–Ω–¥—É)

In [12]:
df1=pd.Series(np.arange(10, 99))
print(df1)
print('Min:', df1.min(), 'Max:', df1.max(), 'Median:', df1.median(), 
      '25pers:', df1.quantile(q = 0.25), '75pers:', df1.quantile(q = 0.75))

0     10
1     11
2     12
3     13
4     14
5     15
6     16
7     17
8     18
9     19
10    20
11    21
12    22
13    23
14    24
15    25
16    26
17    27
18    28
19    29
20    30
21    31
22    32
23    33
24    34
25    35
26    36
27    37
28    38
29    39
      ..
59    69
60    70
61    71
62    72
63    73
64    74
65    75
66    76
67    77
68    78
69    79
70    80
71    81
72    82
73    83
74    84
75    85
76    86
77    87
78    88
79    89
80    90
81    91
82    92
83    93
84    94
85    95
86    96
87    97
88    98
Length: 89, dtype: int32
Min: 10 Max: 98 Median: 54.0 25pers: 32.0 75pers: 76.0

In [13]:
df1.describe()

count    89.000000
mean     54.000000
std      25.836021
min      10.000000
25%      32.000000
50%      54.000000
75%      76.000000
max      98.000000
dtype: float64

6. –ö–∞–∫ –ø–æ–ª—É—á–∏—Ç—å —á–∞—Å—Ç–æ—Ç—É\–¥–æ–ª—é –¥–ª—è –≤—Å–µ—Ö —É–Ω–∏–∫–∞–ª—å–Ω—ã—Ö –æ–±—ä–µ–∫—Ç–æ–≤ –≤ series? (‚òÖ‚òÜ‚òÜ)

In [6]:
df1=pd.Series(['a', 'b', 'c', 'g', 'v', 'a', 'a', 'a', 'u', 'a', 'b', 'c', 'c'])

df1.value_counts(normalize=True)

a    0.384615
c    0.230769
b    0.153846
u    0.076923
g    0.076923
v    0.076923
dtype: float64

7. –ö–∞–∫ –æ—Å—Ç–∞–≤–∏—Ç—å —Ç–æ–ª—å–∫–æ —Ç–æ–ø-2 —Å–∞–º—ã—Ö —á–∞—Å—Ç–æ –≤—Å—Ç—Ä–µ—á–∞—é—â–∏—Ö—Å—è –∑–Ω–∞—á–µ–Ω–∏–π, –∞ –≤—Å–µ –æ—Å—Ç–∞–ª—å–Ω—ã–µ –∑–Ω–∞—á–µ–Ω–∏—è –∑–∞–º–µ–Ω–∏—Ç—å –Ω–∞ 'other'?  (‚òÖ‚òÖ‚òÜ)

In [285]:
df1=pd.Series(['a', 'b', 'c', 'g', 'v', 'a', 'a', 'a', 'u', 'a', 'b', 'c', 'c'])
df2 = df1.value_counts()
df1.replace(df2.index[2:], 'other')

0         a
1     other
2         c
3     other
4     other
5         a
6         a
7         a
8     other
9         a
10    other
11        c
12        c
dtype: object

8. –ö–∞–∫ —Ä–∞–∑–±–∏—Ç—å –∫–æ–ª–æ–Ω–∫—É —Å —á–∏—Å–ª–æ–≤—ã–º–∏ –∑–Ω–∞—á–µ–Ω–∏—è–º–∏ –Ω–∞ 10 –≥—Ä—É–ø–ø –æ–¥–∏–Ω–∞–∫–æ–≤–æ–≥–æ —Ä–∞–∑–º–µ—Ä–∞?  (‚òÖ‚òÖ‚òÜ)

(hint: pd.qcut)

In [776]:
s = pd.Series(np.random.random(20))
print(s, '\n')
print(pd.qcut(s,10))

0     0.103931
1     0.932978
2     0.391783
3     0.953667
4     0.508095
5     0.808580
6     0.958709
7     0.776109
8     0.607297
9     0.497122
10    0.075268
11    0.228365
12    0.700478
13    0.678039
14    0.472431
15    0.911584
16    0.465940
17    0.061823
18    0.863975
19    0.315043
dtype: float64

0      (0.101, 0.298]
1      (0.873, 0.935]
2      (0.298, 0.444]
3      (0.935, 0.959]
4      (0.487, 0.558]
5      (0.786, 0.873]
6      (0.935, 0.959]
7      (0.687, 0.786]
8      (0.558, 0.687]
9      (0.487, 0.558]
10    (0.0608, 0.101]
11     (0.101, 0.298]
12     (0.687, 0.786]
13     (0.558, 0.687]
14     (0.444, 0.487]
15     (0.873, 0.935]
16     (0.444, 0.487]
17    (0.0608, 0.101]
18     (0.786, 0.873]
19     (0.298, 0.444]
dtype: category
Categories (10, interval[float64]): [(0.0608, 0.101] < (0.101, 0.298] < (0.298, 0.444] < (0.444, 0.487] ... (0.687, 0.786] < (0.786, 0.873] < (0.873, 0.935] < (0.935, 0.959]]

9. –ö–∞–∫ –Ω–∞–π—Ç–∏ –ø–æ–∑–∏—Ü–∏–∏ —á–∏—Å–µ–ª, –∫–æ—Ç–æ—Ä—ã–µ –¥–µ–ª—è—Ç—Å—è –Ω–∞ 3 –±–µ–∑ –æ—Å—Ç–∞—Ç–∫–∞ –∏–∑ series?  (‚òÖ‚òÖ‚òÜ)

(–º–æ–∂–Ω–æ —Å –ø–æ–º–æ—â—å—é numpy –∏ —Å –ø–æ–º–æ—â—å—é pandas)

In [777]:
print(df1, '\n')

print(df1[df1%3==0].index)

0     10
1     11
2     12
3     13
4     14
      ..
84    94
85    95
86    96
87    97
88    98
Length: 89, dtype: int64

Int64Index([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50,
            53, 56, 59, 62, 65, 68, 71, 74, 77, 80, 83, 86],
           dtype='int64')

10. –ö–∞–∫ –∏–∑–≤–ª–µ—á—å –∏–∑ series —Å—Ç—Ä–æ–∫–∏ –ø–æ –∏–Ω–¥–µ–∫—Å–∞–º?  (‚òÖ‚òÜ‚òÜ)

In [32]:
s = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]

for i in pos:   
    print(s[i:], '\n')

0     a
1     b
2     c
3     d
4     e
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object
0     a
1     b
2     c
3     d
4     e
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object

4     e
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object

8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object

14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object

20    u
21    v
22    w
23    x
24    y
25    z
dtype: object

11. –ö–∞–∫ —Å–¥–µ–ª–∞—Ç—å stack –¥–≤—É—Ö series –≤–µ—Ä—Ç–∏–∫–∞–ª—å–Ω–æ –∏ –≥–æ—Ä–∏–∑–æ–Ω—Ç–∞–ª—å–Ω–æ? (‚òÖ‚òÜ‚òÜ)

(hint: pd.append, pd.concat)

In [779]:
s1 = pd.Series(range(5))
s2 = pd.Series(list('abcde'))

print(pd.concat([s1,s2],axis=1), '\n')
print(pd.concat([s1,s2]))

   0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e

0    0
1    1
2    2
3    3
4    4
0    a
1    b
2    c
3    d
4    e
dtype: object

12. –ö–∞–∫ –ø–æ–ª—É—á–∏—Ç—å –ø–æ–∑–∏—Ü–∏–∏ —Å—Ç—Ä–æ–∫ –∏–∑ series A –∏–∑ –¥—Ä—É–≥–æ–≥–æ series B? (‚òÖ‚òÜ‚òÜ)

(–º–æ–∂–Ω–æ —Å –ø–æ–º–æ—â—å—é numpy –∏ —Å –ø–æ–º–æ—â—å—é pandas)

In [10]:
s1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
s2 = pd.Series([1, 3, 10, 13])

s1[s1.isin(s2)].index

Int64Index([0, 4, 5, 8], dtype='int64')

13. –ö–∞–∫ –≤—ã—á–∏—Å–ª–∏—Ç—å —Å—Ä–µ–¥–Ω–µ–∫–≤–∞–¥—Ä–∞—Ç–∏—á–µ—Å–∫—É—é –æ—à–∏–±–∫—É –¥–ª—è –∏—Å—Ç–∏–Ω–Ω—ã—Ö –∏ –ø—Ä–µ–¥—Å–∫–∞–∑–∞–Ω–Ω—ã—Ö –∑–Ω–∞—á–µ–Ω–∏–π? (‚òÖ‚òÖ‚òÜ)

In [10]:
truth = pd.Series(range(10))
pred = pd.Series(range(10)) + np.random.random(10)

from sklearn.metrics import mean_squared_error

mean_squared_error(truth, pred)

0.5011450032264304

14. –ö–∞–∫ –∫–æ–Ω–≤–µ—Ä—Ç–∏—Ä–æ–≤–∞—Ç—å –∫–∞–∂–¥—ã–π –ø–µ—Ä–≤—ã–π —ç–ª–µ–º–µ–Ω—Ç —Å—Ç—Ä–æ–∫–µ –≤ series –≤ –≤–µ—Ä—Ö–Ω–∏–π —Ä–µ–≥–∏—Å—Ç—Ä? (‚òÖ‚òÖ‚òÜ)

In [33]:
s = pd.Series(['how', 'to', 'kick', 'ass?'])
print(s.str.capitalize())

0     How
1      To
2    Kick
3    Ass?
dtype: object

15. –ö–∞–∫ –ø–æ—Å—á–∏—Ç–∞—Ç—å –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ —Å–∏–º–≤–æ–ª–æ–≤ –≤ –∫–∞–∂–¥–æ–π —Å—Ç—Ä–æ–∫–µ? (‚òÖ‚òÖ‚òÜ)

In [40]:
s = pd.Series(['how', 'to', 'kick', 'ass?'])

print(s.str.len())

0    3
1    2
2    4
3    4
dtype: int64

16. –ö–∞–∫ –ø—Ä–µ–æ–±—Ä–∞–∑–æ–≤–∞—Ç—å –¥–∞—Ç—ã –≤ –≤–∏–¥–µ —Å—Ç—Ä–æ–∫ –≤ timeseries?  (‚òÖ‚òÜ‚òÜ)

(hint: pd.to_datetime)

In [783]:
s = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

s = pd.to_datetime(s)
print(s)

0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]

17. –ö–∞–∫ –ø–æ–ª—É—á–∏—Ç—å –¥–µ–Ω—å –º–µ—Å—è—Ü–∞, –Ω–æ–º–µ—Ä –Ω–µ–¥–µ–ª–∏, –¥–µ–Ω—å –≥–æ–¥–∞ –∏ –¥–µ–Ω—å –Ω–µ–¥–µ–ª–∏ –∏–∑ –¥–∞—Ç—ã –≤ –≤–∏–¥–µ —Å—Ç—Ä–æ–∫–∏? (‚òÖ‚òÖ‚òÜ)

In [76]:
s = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

s = pd.to_datetime(s)
print(s,'\n')

for i in range(len(s)):
    print("Date: ", s[i])
    print("Week number: ", s[i].weekofyear)
    print("Day number of year: ", s[i].dayofyear)
    print("Day of week: ", s[i].dayofweek, '\n')
    
## –∫–∞–∫–∞—è-—Ç–æ —Ñ–∏–≥–Ω—è —Å –Ω–æ–º–µ—Ä–æ–º –Ω–µ–¥–µ–ª–∏ –ø–µ—Ä–≤–æ–π –¥–∞—Ç—ã

0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]

Date:  2010-01-01 00:00:00
Week number:  53
Day number of year:  1
Day of week:  4

Date:  2011-02-02 00:00:00
Week number:  5
Day number of year:  33
Day of week:  2

Date:  2012-03-03 00:00:00
Week number:  9
Day number of year:  63
Day of week:  5

Date:  2013-04-04 00:00:00
Week number:  14
Day number of year:  94
Day of week:  3

Date:  2014-05-05 00:00:00
Week number:  19
Day number of year:  125
Day of week:  0

Date:  2015-06-06 12:20:00
Week number:  23
Day number of year:  157
Day of week:  5

18. –ö–∞–∫ –∫–æ–Ω–≤–µ—Ä—Ç–∏—Ä–æ–≤–∞—Ç—å –¥–∞—Ç—É –∏–∑ —Ñ–æ—Ä–º–∞—Ç–∞ –º–µ—Å—è—Ü-–≥–æ–¥ –≤ —Ñ–æ—Ä–º–∞—Ç –≥–æ–¥-–º–µ—Å—è—Ü-–ø–µ—Ä–≤–æ–µ —á–∏—Å–ª–æ? (‚òÖ‚òÖ‚òÜ)

(hint: .strftime('%Y-%m-%d'))

In [7]:
s = pd.Series(['Jan 2017', 'Feb 2019', 'Mar 2012'])

from datetime import datetime

s = pd.to_datetime(s)

s.apply(lambda x: x.strftime('%d-%m-%Y'))

0    01-01-2017
1    01-02-2019
2    01-03-2012
dtype: object

19. –ö–∞–∫ –æ—Ç—Ñ–∏–ª—å—Ç—Ä–æ–≤–∞—Ç—å —Å–ª–æ–≤–∞, —Å–æ–¥–µ—Ä–∂–∞—â–∏–µ –Ω–µ –º–µ–Ω–µ–µ 2 –≥–ª–∞—Å–Ω—ã—Ö? (‚òÖ‚òÖ‚òÜ)

In [21]:
s = pd.Series(['Kitty', 'Cat', 'Plan', 'Python', 'Money'])

# –≤—ã–≤–æ–∂—É —Å–ª–æ–≤–æ —Å –Ω–µ –º–µ–Ω–µ–µ —á–µ–º –¥–≤—É–º—è –≥–ª–∞—Å–Ω—ã–º–∏
# –Ω–æ —Ç–æ–ª—å–∫–æ print(glas) –≤—ã–≤–µ–¥–µ—Ç –≥–¥–µ —Å–∫–æ–ª—å–∫–æ –≥–ª–∞—Å–Ω—ã—Ö –≤ —Å–µ—Ä–∏–∞—Å–µ

s[s.str.count('[AEIOUaeiou]')>1]

Money

<img src="gifs/sleep.gif" width="400">

20. –ó–∞–ø–æ–ª–Ω–∏—Ç–µ –≤—Å–µ –ø—Ä–æ–ø—É—â–µ–Ω–Ω—ã–µ –¥–∞—Ç—ã –æ—Ç –º–∏–Ω–∏–º–∞–ª—å–Ω–æ–π –¥–æ –º–∞–∫—Å–∏–º–∞–ª—å–Ω–æ–π, –∑–Ω–∞—á–µ–Ω–∏—è –ø—Ä–∏ —ç—Ç–æ–º –¥–æ–∂–Ω—ã –±—ã—Ç—å —Ä–∞–≤–Ω—ã –ø—Ä–µ–¥—ã–¥—É—â–µ–π –Ω–µ –ø—Ä–æ–ø—É—â–µ–Ω–æ–π –¥–∞—Ç–µ (‚òÖ‚òÖ‚òÖ)

In [25]:
s = pd.Series([1,10,3,np.nan], index = pd.to_datetime(['2000-01-01', '2000-01-03', '2000-01-06', '2000-01-08']))

print(s)
print()
a = s.index

new_ind = []

for i in range(len(a)-1):
    new_ind.append(dict(pd.date_range(a[i], periods = (a[i+1].day-a[i].day))))

print(l)

2000-01-01     1.0
2000-01-03    10.0
2000-01-06     3.0
2000-01-08     NaN
dtype: float64

TypeError: cannot convert dictionary update sequence element #0 to a sequence

In [587]:
s = pd.Series([1,10,3,np.nan], index=pd.to_datetime(['2000-01-01', '2000-01-03', '2000-01-06', '2000-01-08']))
dates=pd.date_range(start=s.index.min(), end=s.index.max())
print(dates)

for date in dates:
    if date not in s:
        s[date] = 
        
s = s.sort_index()
print(s)

DatetimeIndex(['2000-01-01', '2000-01-02', '2000-01-03', '2000-01-04',
               '2000-01-05', '2000-01-06', '2000-01-07', '2000-01-08'],
              dtype='datetime64[ns]', freq='D')

KeyError: Timestamp('2000-01-02 00:00:00', freq='D')

21. –°—á–∏—Ç–∞–π—Ç–µ —Ñ–∞–π–ª –∏–∑ CSV-—Ñ–∞–π–ª–∞ –ø–æ —Å—Ç—Ä–æ—á–Ω–æ –∏ –¥–æ–±–∞–≤—å—Ç–µ —Å—á–∏—Ç–∞–Ω–Ω—ã–µ —Å—Ç—Ä–æ–∫–∏ –≤ –¥–∞—Ç–∞—Ñ—Ä–µ–π–º (—Ñ–∞–π–ª data/BostonHousing.csv)?  (‚òÖ‚òÖ‚òÜ)

(hint: csv reader)

In [818]:
data = pd.read_csv('BostonHousing.csv', sep = ',')
print(data)
type(data)

        crim    zn  indus  chas    nox     rm   age     dis  rad  tax  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273

     ptratio       b  lstat  medv
0       15.3  396.90   4.98  24.0
1       17.8  396.90   9.14  21.6
2       17.8  392.83   4.03  34.7
3       18.7  394.63   2.94  33.4
4       18.7  396.90   5.33  36.2
..       ...     ...    ...   ...
501     21.0  391.99   9.67  22.4
502     21.0  396.90   9.08  20.6
503     21.0  396.90   5.64  23.9
504     21.0  393.45   6.48  22.0
505     21.0  396.90   7.88  11.9

[506 rows x 14 columns]

pandas.core.frame.DataFrame

22. –ö–∞–∫ –∏–∑–º–µ–Ω–∏—Ç—å –∑–Ω–∞—á–µ–Ω–∏—è —Å—Ç–æ–ª–±—Ü–∞ –ø—Ä–∏ –∏–º–ø–æ—Ä—Ç–µ csv –≤ —Ñ—Ä–µ–π–º –¥–∞–Ω–Ω—ã—Ö?
–ò–º–ø–æ—Ä—Ç–∏—Ä—É–π—Ç–µ –¥–∞—Ç–∞—Å–µ—Ç —Å –ø–æ–º–æ—â—å—é pd.read_csv, –Ω–æ –∫–æ–ª–æ–Ω–∫—É 'medv' (median house value) –∏–∑–º–µ–Ω–∏—Ç–µ —Ç–∞–∫, —á—Ç–æ –µ—Å–ª–∏ value < 25 = ‚ÄòLow‚Äô –∏ –µ—Å–ª–∏ > 25 = ‚ÄòHigh‚Äô.  (‚òÖ‚òÖ‚òÜ)

(hint: pd.read_csv(....., converts={}))

In [838]:
def func(x):
    x = float(x)
    if x > 25.:
        x = 'Hight'
    else:
        x = 'Low'
    return x

In [839]:
a = pd.read_csv('BostonHousing.csv',  sep = ',', converters = {'medv': func})

print(a)

#hard... so hard!
#x = float(x) - –¥–≤–∞ –¥–Ω—è –¥—É–º–∞–ª–∞, —á—Ç–æ –µ–º—É –Ω—É–∂–Ω–æ. –∞ –æ–∫–∞–∑—ã–≤–∞–µ—Ç—Å—è, –≤—Å–µ–≥–æ –ª–∏—à—å —ç—Ç–æ..........

        crim    zn  indus  chas    nox     rm   age     dis  rad  tax  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273

     ptratio       b  lstat   medv
0       15.3  396.90   4.98    Low
1       17.8  396.90   9.14    Low
2       17.8  392.83   4.03  Hight
3       18.7  394.63   2.94  Hight
4       18.7  396.90   5.33  Hight
..       ...     ...    ...    ...
501     21.0  391.99   9.67    Low
502     21.0  396.90   9.08    Low
503     21.0  396.90   5.64    Low
504     21.0  393.45   6.48    Low
505     21.0  396.90   7.88    Low

[506 rows x 14 columns]

23. –ö–∞–∫ –∏–º–ø–æ—Ä—Ç–∏—Ä–æ–≤–∞—Ç—å —Ç–æ–ª—å–∫–æ —É–∫–∞–∑–∞–Ω–Ω—ã–µ —Å—Ç–æ–ª–±—Ü—ã('crim' –∏ 'medv') –∏ —Ç–æ–ª—å–∫–æ n —Å—Ç—Ä–æ–∫ –∏–∑ CSV-—Ñ–∞–π–ª–∞?  (‚òÖ‚òÜ‚òÜ)

In [200]:
a = pd.read_csv('BostonHousing.csv', usecols = {'crim','medv'}, nrows = 15)
print(a)

       crim  medv
0   0.00632  24.0
1   0.02731  21.6
2   0.02729  34.7
3   0.03237  33.4
4   0.06905  36.2
5   0.02985  28.7
6   0.08829  22.9
7   0.14455  27.1
8   0.21124  16.5
9   0.17004  18.9
10  0.22489  15.0
11  0.11747  18.9
12  0.09378  21.7
13  0.62976  20.4
14  0.63796  18.2

24. –ö–∞–∫ –ø–æ–ª—É—á–∏—Ç—å –∫–æ–ª-–≤–æ —Å—Ç—Ä–æ–∫, –∫–æ–ª-–≤–æ —Å—Ç–æ–ª–±—Ü–æ–≤, —Ç–∏–ø —Å—Ç–æ–ª–±—Ü–æ–≤, –∫–æ–ª-–≤–æ —Å—Ç–æ–ª–±—Ü–æ–≤ —Å —Ç–∞–∫–∏–º —Ç–∏–ø–æ–º –¥–∞–Ω–Ω—ã—Ö, –∏—Ç–æ–≥–æ–≤—É—é —Å—Ç–∞—Ç–∏—Å—Ç–∏–∫—É –∫–∞–∂–¥–æ–≥–æ —Å—Ç–æ–ª–±—Ü–∞ –¥–∞—Ç–∞—Ñ—Ä–µ–π–º–∞?  (‚òÖ‚òÜ‚òÜ)

In [217]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

print(df.shape, '\n')

print(df.dtypes, '\n')

print(df.dtypes.value_counts(), '\n')

print(df.describe)

(93, 27)

Manufacturer           object
Model                  object
Type                   object
Min.Price             float64
Price                 float64
Max.Price             float64
MPG.city              float64
MPG.highway           float64
AirBags                object
DriveTrain             object
Cylinders              object
EngineSize            float64
Horsepower            float64
RPM                   float64
Rev.per.mile          float64
Man.trans.avail        object
Fuel.tank.capacity    float64
Passengers            float64
Length                float64
Wheelbase             float64
Width                 float64
Turn.circle           float64
Rear.seat.room        float64
Luggage.room          float64
Weight                float64
Origin                 object
Make                   object
dtype: object

float64    18
object      9
dtype: int64

<bound method NDFrame.describe of    Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small       12.9   15.9       18.8      25.0
1           NaN   Legend  Midsize       29.2   33.9       38.7      18.0
2          Audi       90  Compact       25.9   29.1       32.3      20.0
3          Audi      100  Midsize        NaN   37.7       44.6      19.0
4           BMW     535i  Midsize        NaN   30.0        NaN      22.0
..          ...      ...      ...        ...    ...        ...       ...
88   Volkswagen  Eurovan      Van       16.6   19.7       22.7      17.0
89   Volkswagen   Passat  Compact       17.6   20.0       22.4      21.0
90   Volkswagen  Corrado   Sporty       22.9   23.3       23.7      18.0
91        Volvo      240  Compact       21.8   22.7       23.5      21.0
92          NaN      850  Midsize       24.8   26.7       28.5      20.0

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31.0                None      Front  ...        5.0   177.0
1          25.0  Driver & Passenger      Front  ...        5.0   195.0
2          26.0         Driver only      Front  ...        5.0   180.0
3          26.0  Driver & Passenger        NaN  ...        6.0   193.0
4          30.0                 NaN       Rear  ...        4.0   186.0
..          ...                 ...        ...  ...        ...     ...
88         21.0                None      Front  ...        7.0   187.0
89         30.0                None      Front  ...        5.0   180.0
90         25.0                None      Front  ...        4.0   159.0
91         28.0         Driver only       Rear  ...        5.0   190.0
92         28.0  Driver & Passenger      Front  ...        5.0   184.0

    Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0       102.0   68.0         37.0           26.5           NaN  2705.0
1       115.0   71.0         38.0           30.0          15.0  3560.0
2       102.0   67.0         37.0           28.0          14.0  3375.0
3       106.0    NaN         37.0           31.0          17.0  3405.0
4       109.0   69.0         39.0           27.0          13.0  3640.0
..        ...    ...          ...            ...           ...     ...
88      115.0   72.0         38.0           34.0           NaN  3960.0
89      103.0   67.0         35.0           31.5          14.0  2985.0
90       97.0   66.0         36.0           26.0          15.0  2810.0
91      104.0   67.0         37.0           29.5          14.0  2985.0
92      105.0   69.0         38.0           30.0          15.0  3245.0

     Origin                Make
0   non-USA       Acura Integra
1   non-USA        Acura Legend
2   non-USA             Audi 90
3   non-USA            Audi 100
4   non-USA            BMW 535i
..      ...                 ...
88      NaN  Volkswagen Eurovan
89  non-USA   Volkswagen Passat
90  non-USA  Volkswagen Corrado
91  non-USA           Volvo 240
92  non-USA           Volvo 850

[93 rows x 27 columns]>

25. –ö–∞–∫ –∏–∑–≤–ª–µ—á—å –Ω–æ–º–µ—Ä —Å—Ç—Ä–æ–∫–∏ –∏ —Å—Ç–æ–ª–±—Ü–∞ –∫–æ–Ω–∫—Ä–µ—Ç–Ω–æ–π —è—á–µ–π–∫–∏ —Å –∑–∞–¥–∞–Ω–Ω—ã–º –∫—Ä–∏—Ç–µ—Ä–∏–µ–º? (‚òÖ‚òÜ‚òÜ)

In [28]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

print('Manufacturer with highest price: ', df['Manufacturer'][df['Max.Price'].idxmax()])

print('Price: ', df['Max.Prioce'].max())

Manufacturer with highest price:  Mercedes-Benz
Price:  80.0

26. –ü–µ—Ä–µ–∏–º–µ–Ω–Ω—É–π—Ç–µ –∫–æ–ª–æ–Ω–∫—É Type –≤ CarType, –≤ —Å—Ç–æ–ª–±—Ü–∞—Ö —Å '.' –≤ –Ω–∞–∑–≤–∞–Ω–∏–∏ –∑–∞–º–µ–Ω–∏—Ç–µ –µ—ë –Ω–∞ '_'. –ö–∞–∫ –¥–æ–±–∞–≤–∏—Ç—å –∫–æ –≤—Å–µ–º –Ω–∞–∑–≤–∞–Ω–∏—è–º –∫–æ–ª–æ–Ω–æ–∫ —Å—É—Ñ—Ñ–∏–∫—Å—ã?  (‚òÖ‚òÜ‚òÜ)

In [897]:
import re

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

df = df.rename(columns={'Type': 'CarType'})

df.columns = [col.replace('.', '_') for col in df.columns]

print(df)
#print(df.add_suffix('_item'))

   Manufacturer    Model  CarType  Min_Price  Price  Max_Price  MPG_city  ...  \
0         Acura  Integra    Small       12.9   15.9       18.8      25.0  ...
1           NaN   Legend  Midsize       29.2   33.9       38.7      18.0  ...
2          Audi       90  Compact       25.9   29.1       32.3      20.0  ...
3          Audi      100  Midsize        NaN   37.7       44.6      19.0  ...
4           BMW     535i  Midsize        NaN   30.0        NaN      22.0  ...
..          ...      ...      ...        ...    ...        ...       ...  ...
88   Volkswagen  Eurovan      Van       16.6   19.7       22.7      17.0  ...
89   Volkswagen   Passat  Compact       17.6   20.0       22.4      21.0  ...
90   Volkswagen  Corrado   Sporty       22.9   23.3       23.7      18.0  ...
91        Volvo      240  Compact       21.8   22.7       23.5      21.0  ...
92          NaN      850  Midsize       24.8   26.7       28.5      20.0  ...

    Width Turn_circle Rear_seat_room Luggage_room  Weight   Origin  \
0    68.0        37.0           26.5          NaN  2705.0  non-USA
1    71.0        38.0           30.0         15.0  3560.0  non-USA
2    67.0        37.0           28.0         14.0  3375.0  non-USA
3     NaN        37.0           31.0         17.0  3405.0  non-USA
4    69.0        39.0           27.0         13.0  3640.0  non-USA
..    ...         ...            ...          ...     ...      ...
88   72.0        38.0           34.0          NaN  3960.0      NaN
89   67.0        35.0           31.5         14.0  2985.0  non-USA
90   66.0        36.0           26.0         15.0  2810.0  non-USA
91   67.0        37.0           29.5         14.0  2985.0  non-USA
92   69.0        38.0           30.0         15.0  3245.0  non-USA

                  Make
0        Acura Integra
1         Acura Legend
2              Audi 90
3             Audi 100
4             BMW 535i
..                 ...
88  Volkswagen Eurovan
89   Volkswagen Passat
90  Volkswagen Corrado
91           Volvo 240
92           Volvo 850

[93 rows x 27 columns]

27. –ü—Ä–æ–≤–µ—Ä—å—Ç–µ –µ—Å—Ç—å –ª–∏ –≤ –¥–∞—Ç–∞—Ñ—Ä–µ–π–º–µ –ø—Ä–æ–ø—É—Å–∫–∏? –ï—Å–ª–∏ –¥–∞, –ø–æ—Å—á–∏—Ç–∞–π—Ç–µ –∫–æ–ª-–≤–æ nan\none –≤ –∫–∞–∂–¥–æ–º —Å—Ç–æ–ª–±—Ü–µ –¥–∞—Ç–∞—Ñ—Ä–µ–π–º–∞  (‚òÖ‚òÖ‚òÜ)

In [282]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

pd.isnull(df).sum()

Manufacturer           4
Model                  1
Type                   3
Min.Price              7
Price                  2
Max.Price              5
MPG.city               9
MPG.highway            2
AirBags                6
DriveTrain             7
Cylinders              5
EngineSize             2
Horsepower             7
RPM                    3
Rev.per.mile           6
Man.trans.avail        5
Fuel.tank.capacity     8
Passengers             2
Length                 4
Wheelbase              1
Width                  6
Turn.circle            5
Rear.seat.room         4
Luggage.room          19
Weight                 7
Origin                 5
Make                   3
dtype: int64

28. –ö–∞–∫ –∑–∞–º–µ–Ω–∏—Ç—å –æ—Ç—Å—É—Ç—Å—Ç–≤—É—é—â–∏–µ –∑–Ω–∞—á–µ–Ω–∏—è –Ω–µ—Å–∫–æ–ª—å–∫–∏—Ö —á–∏—Å–ª–æ–≤—ã—Ö —Å—Ç–æ–ª–±—Ü–æ–≤ —Å—Ä–µ–¥–Ω–∏–º?  (‚òÖ‚òÖ‚òÜ)

In [280]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

df.fillna(df.mean())

,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,DriveTrain,...,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make
0,Acura,Integra,Small,12.900000,15.9,18.800000,25.0,31.0,None,Front,...,5.0,177.0,102.0,68.000000,37.0,26.5,13.986486,2705.0,non-USA,Acura Integra
1,NaN,Legend,Midsize,29.200000,33.9,38.700000,18.0,25.0,Driver & Passenger,Front,...,5.0,195.0,115.0,71.000000,38.0,30.0,15.000000,3560.0,non-USA,Acura Legend
2,Audi,90,Compact,25.900000,29.1,32.300000,20.0,26.0,Driver only,Front,...,5.0,180.0,102.0,67.000000,37.0,28.0,14.000000,3375.0,non-USA,Audi 90
3,Audi,100,Midsize,17.118605,37.7,44.600000,19.0,26.0,Driver & Passenger,NaN,...,6.0,193.0,106.0,69.448276,37.0,31.0,17.000000,3405.0,non-USA,Audi 100
4,BMW,535i,Midsize,17.118605,30.0,21.459091,22.0,30.0,NaN,Rear,...,4.0,186.0,109.0,69.000000,39.0,27.0,13.000000,3640.0,non-USA,BMW 535i
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,16.600000,19.7,22.700000,17.0,21.0,None,Front,...,7.0,187.0,115.0,72.000000,38.0,34.0,13.986486,3960.0,NaN,Volkswagen Eurovan
89,Volkswagen,Passat,Compact,17.600000,20.0,22.400000,21.0,30.0,None,Front,...,5.0,180.0,103.0,67.000000,35.0,31.5,14.000000,2985.0,non-USA,Volkswagen Passat
90,Volkswagen,Corrado,Sporty,22.900000,23.3,23.700000,18.0,25.0,None,Front,...,4.0,159.0,97.0,66.000000,36.0,26.0,15.000000,2810.0,non-USA,Volkswagen Corrado
91,Volvo,240,Compact,21.800000,22.7,23.500000,21.0,28.0,Driver only,Rear,...,5.0,190.0,104.0,67.000000,37.0,29.5,14.000000,2985.0,non-USA,Volvo 240
92,NaN,850,Midsize,24.800000,26.7,28.500000,20.0,28.0,Driver & Passenger,Front,...,5.0,184.0,105.0,69.000000,38.0,30.0,15.000000,3245.0,non-USA,Volvo 850

29. –ö–∞–∫ –≤—ã–±—Ä–∞—Ç—å –∫–æ–Ω–∫—Ä–µ—Ç–Ω—ã–π —Å—Ç–æ–ª–±–µ—Ü –∏–∑ –¥–∞—Ç–∞—Ñ—Ä–µ–π–º–∞ –≤ –∫–∞—á–µ—Å—Ç–≤–µ –¥–∞—Ç–∞—Ñ—Ä–µ–π–º–∞, –∞ –Ω–µ series?  (‚òÖ‚òÜ‚òÜ)

In [52]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

print(df)

df[['Model']]

   Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small       12.9   15.9       18.8      25.0
1           NaN   Legend  Midsize       29.2   33.9       38.7      18.0
2          Audi       90  Compact       25.9   29.1       32.3      20.0
3          Audi      100  Midsize        NaN   37.7       44.6      19.0
4           BMW     535i  Midsize        NaN   30.0        NaN      22.0
..          ...      ...      ...        ...    ...        ...       ...
88   Volkswagen  Eurovan      Van       16.6   19.7       22.7      17.0
89   Volkswagen   Passat  Compact       17.6   20.0       22.4      21.0
90   Volkswagen  Corrado   Sporty       22.9   23.3       23.7      18.0
91        Volvo      240  Compact       21.8   22.7       23.5      21.0
92          NaN      850  Midsize       24.8   26.7       28.5      20.0

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31.0                None      Front  ...        5.0   177.0
1          25.0  Driver & Passenger      Front  ...        5.0   195.0
2          26.0         Driver only      Front  ...        5.0   180.0
3          26.0  Driver & Passenger        NaN  ...        6.0   193.0
4          30.0                 NaN       Rear  ...        4.0   186.0
..          ...                 ...        ...  ...        ...     ...
88         21.0                None      Front  ...        7.0   187.0
89         30.0                None      Front  ...        5.0   180.0
90         25.0                None      Front  ...        4.0   159.0
91         28.0         Driver only       Rear  ...        5.0   190.0
92         28.0  Driver & Passenger      Front  ...        5.0   184.0

    Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0       102.0   68.0         37.0           26.5           NaN  2705.0
1       115.0   71.0         38.0           30.0          15.0  3560.0
2       102.0   67.0         37.0           28.0          14.0  3375.0
3       106.0    NaN         37.0           31.0          17.0  3405.0
4       109.0   69.0         39.0           27.0          13.0  3640.0
..        ...    ...          ...            ...           ...     ...
88      115.0   72.0         38.0           34.0           NaN  3960.0
89      103.0   67.0         35.0           31.5          14.0  2985.0
90       97.0   66.0         36.0           26.0          15.0  2810.0
91      104.0   67.0         37.0           29.5          14.0  2985.0
92      105.0   69.0         38.0           30.0          15.0  3245.0

     Origin                Make
0   non-USA       Acura Integra
1   non-USA        Acura Legend
2   non-USA             Audi 90
3   non-USA            Audi 100
4   non-USA            BMW 535i
..      ...                 ...
88      NaN  Volkswagen Eurovan
89  non-USA   Volkswagen Passat
90  non-USA  Volkswagen Corrado
91  non-USA           Volvo 240
92  non-USA           Volvo 850

[93 rows x 27 columns]

      Model
0   Integra
1    Legend
2        90
3       100
4      535i
..      ...
88  Eurovan
89   Passat
90  Corrado
91      240
92      850

[93 rows x 1 columns]

30. –ö–∞–∫ –∏–∑–º–µ–Ω–∏—Ç—å –ø–æ—Ä—è–¥–æ–∫ —Å—Ç–æ–ª–±—Ü–æ–≤ –¥–∞–Ω–Ω—ã—Ö? (‚òÜ‚òÜ‚òÜ)

In [869]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# print(df, '\n')

df[['Min_Price', 'Model', 'Manufacturer',  'Type']].head()

                  Make Manufacturer    Model     Type  Min.Price  Price  \
0        Acura Integra        Acura  Integra    Small       12.9   15.9
1         Acura Legend          NaN   Legend  Midsize       29.2   33.9
2              Audi 90         Audi       90  Compact       25.9   29.1
3             Audi 100         Audi      100  Midsize        NaN   37.7
4             BMW 535i          BMW     535i  Midsize        NaN   30.0
..                 ...          ...      ...      ...        ...    ...
88  Volkswagen Eurovan   Volkswagen  Eurovan      Van       16.6   19.7
89   Volkswagen Passat   Volkswagen   Passat  Compact       17.6   20.0
90  Volkswagen Corrado   Volkswagen  Corrado   Sporty       22.9   23.3
91           Volvo 240        Volvo      240  Compact       21.8   22.7
92           Volvo 850          NaN      850  Midsize       24.8   26.7

    Max.Price  ...  Wheelbase  Width Turn.circle Rear.seat.room Luggage.room  \
0        18.8  ...      102.0   68.0        37.0           26.5          NaN
1        38.7  ...      115.0   71.0        38.0           30.0         15.0
2        32.3  ...      102.0   67.0        37.0           28.0         14.0
3        44.6  ...      106.0    NaN        37.0           31.0         17.0
4         NaN  ...      109.0   69.0        39.0           27.0         13.0
..        ...  ...        ...    ...         ...            ...          ...
88       22.7  ...      115.0   72.0        38.0           34.0          NaN
89       22.4  ...      103.0   67.0        35.0           31.5         14.0
90       23.7  ...       97.0   66.0        36.0           26.0         15.0
91       23.5  ...      104.0   67.0        37.0           29.5         14.0
92       28.5  ...      105.0   69.0        38.0           30.0         15.0

    Weight   Origin
0   2705.0  non-USA
1   3560.0  non-USA
2   3375.0  non-USA
3   3405.0  non-USA
4   3640.0  non-USA
..     ...      ...
88  3960.0      NaN
89  2985.0  non-USA
90  2810.0  non-USA
91  2985.0  non-USA
92  3245.0  non-USA

[93 rows x 27 columns]

31. –ö–∞–∫ —É—Å—Ç–∞–Ω–æ–≤–∏—Ç—å –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ —Å—Ç—Ä–æ–∫ –∏ —Å—Ç–æ–ª–±—Ü–æ–≤, –æ—Ç–æ–±—Ä–∞–∂–∞–µ–º—ã—Ö –≤ –≤—ã–≤–æ–¥–µ? (‚òÜ‚òÜ‚òÜ)

(hint: pd.set_option)

In [302]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
pd.set_option('max_rows',15)
pd.set_option('max_columns',15)
df

,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,...,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make
0,Acura,Integra,Small,12.9,15.9,18.8,25.0,...,68.0,37.0,26.5,NaN,2705.0,non-USA,Acura Integra
1,NaN,Legend,Midsize,29.2,33.9,38.7,18.0,...,71.0,38.0,30.0,15.0,3560.0,non-USA,Acura Legend
2,Audi,90,Compact,25.9,29.1,32.3,20.0,...,67.0,37.0,28.0,14.0,3375.0,non-USA,Audi 90
3,Audi,100,Midsize,NaN,37.7,44.6,19.0,...,NaN,37.0,31.0,17.0,3405.0,non-USA,Audi 100
4,BMW,535i,Midsize,NaN,30.0,NaN,22.0,...,69.0,39.0,27.0,13.0,3640.0,non-USA,BMW 535i
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,16.6,19.7,22.7,17.0,...,72.0,38.0,34.0,NaN,3960.0,NaN,Volkswagen Eurovan
89,Volkswagen,Passat,Compact,17.6,20.0,22.4,21.0,...,67.0,35.0,31.5,14.0,2985.0,non-USA,Volkswagen Passat
90,Volkswagen,Corrado,Sporty,22.9,23.3,23.7,18.0,...,66.0,36.0,26.0,15.0,2810.0,non-USA,Volkswagen Corrado
91,Volvo,240,Compact,21.8,22.7,23.5,21.0,...,67.0,37.0,29.5,14.0,2985.0,non-USA,Volvo 240
92,NaN,850,Midsize,24.8,26.7,28.5,20.0,...,69.0,38.0,30.0,15.0,3245.0,non-USA,Volvo 850

32. –ö–∞–∫ –ø–æ–ª—É—á–∏—Ç—å –Ω–æ–º–µ—Ä —Å—Ç—Ä–æ–∫–∏, –≤ –∫–æ—Ç–æ—Ä–æ–π —Å–æ–¥–µ—Ä–∂–∏—Ç—Å—è –º–∞–∫—Å–∏–º–∞–ª—å–Ω–æ–µ –∑–Ω–∞—á–µ–Ω–∏–µ –≤ —Å—Ç–æ–ª–±—Ü–µ? (‚òÖ‚òÖ‚òÜ)

In [1137]:
df = pd.DataFrame(np.random.randint(1, 30, 30).reshape(10,-1), columns=list('abc'))
print(df, '\n')
print(df['a'].idxmax())
print(df['b'].idxmax())
print(df['c'].idxmax())

    a   b   c
0  19  18   4
1  21  12  18
2   9  24  17
3  18  24  15
4  29  18  10
5  27   2  20
6  18  21  16
7  21  23  19
8  27  29   1
9  21  25  10

4
8
5

33. –ö–∞–∫ –ø–æ–ª—É—á–∏—Ç—å –ø–æ—Å–ª–µ–¥–Ω–∏–µ n —Å—Ç—Ä–æ–∫ –¥–∞—Ç–∞—Ñ—Ä–µ–π–º–∞ —Å —Å—É–º–º–æ–π —Å—Ç—Ä–æ–∫ 100?  (‚òÖ‚òÖ‚òÖ)

In [1200]:
df = pd.DataFrame(np.random.randint(1, 40, 60).reshape(-1,5))

In [1211]:
df

     0   1   2   3   4
0   10  13  39  18   6
1    8  12   4   3  15
2   11   9   2   5  14
3   37  29   9   8  28
4   36  29  19   3   9
5   18  11  25   5   6
6   31  12  36  11  18
7   22  22  37  34  21
8   26  18  15  14  31
9   24   4  13  29  11
10  39  19  11  38  23
11  31  24  23  20   8

In [1220]:
df[(df.sum(axis = 1)) >= 100].tail(n)

     0   1   2   3   4
8   26  18  15  14  31
10  39  19  11  38  23
11  31  24  23  20   8

### –í—ã–±—Ä–æ—Å—ã (–æutliers)

* 5 Ways to Detect Outliers/Anomalies That Every Data Scientist Should Know (Python Code)

https://towardsdatascience.com/5-ways-to-detect-outliers-that-every-data-scientist-should-know-python-code-70a54335a623

34. –ö–∞–∫ –Ω–∞–π—Ç–∏ –∏ –∑–∞–º–µ–Ω–∏—Ç—å –≤—ã–±—Ä–æ—Å—ã –∏–∑ —Å—Ç–æ–ª–±—Ü–∞ Series –∏–ª–∏ –¥–∞—Ç–∞—Ñ—Ä–µ–π–º–∞? (‚òÖ‚òÖ‚òÖ)

–ó–∞–º–µ–Ω–∏—Ç–µ –≤—Å–µ –∑–Ω–∞—á–µ–Ω–∏—è –∏–∑ —Å—Ç–æ–ª–±—Ü–∞ –Ω–∏–∂–µ 5—Ç–æ–≥–æ –∏ –±–æ–ª—å—à–µ 95–≥–æ –ø–µ—Ä—Å–µ–Ω—Ç–∏–ª—è, –Ω–∞ –ø–æ–≥—Ä–∞–Ω–∏—á–Ω—ã–µ –∑–Ω–∞—á–µ–Ω–∏—è.

(hint: .quantile())

In [40]:
s = pd.Series(np.logspace(-2, 2, 30))
print(s)
q1 = s.quantile(.05)
q2 = s.quantile(.95)

0       0.010000
1       0.013738
2       0.018874
3       0.025929
4       0.035622
5       0.048939
6       0.067234
7       0.092367
8       0.126896
9       0.174333
10      0.239503
11      0.329034
12      0.452035
13      0.621017
14      0.853168
15      1.172102
16      1.610262
17      2.212216
18      3.039195
19      4.175319
20      5.736153
21      7.880463
22     10.826367
23     14.873521
24     20.433597
25     28.072162
26     38.566204
27     52.983169
28     72.789538
29    100.000000
dtype: float64

In [62]:
s[s < q1]  = q1
s

0       0.018000
1       0.018000
2       0.018874
3       0.025929
4       0.035622
5       0.048939
6       0.067234
7       0.092367
8       0.126896
9       0.174333
10      0.239503
11      0.329034
12      0.452035
13      0.621017
14      0.853168
15      1.172102
16      1.610262
17      2.212216
18      3.039195
19      4.175319
20      5.736153
21      7.880463
22     10.826367
23     14.873521
24     20.433597
25     28.072162
26     38.566204
27     52.983169
28     72.789538
29    100.000000
dtype: float64

In [63]:
s[s > q2] = q2
s

0      0.018000
1      0.018000
2      0.018874
3      0.025929
4      0.035622
5      0.048939
6      0.067234
7      0.092367
8      0.126896
9      0.174333
10     0.239503
11     0.329034
12     0.452035
13     0.621017
14     0.853168
15     1.172102
16     1.610262
17     2.212216
18     3.039195
19     4.175319
20     5.736153
21     7.880463
22    10.826367
23    14.873521
24    20.433597
25    28.072162
26    38.566204
27    52.983169
28    52.990000
29    52.990000
dtype: float64

35. –ü–æ–ø—Ä–æ–±—É–π—Ç–µ —Ä–µ–∞–ª–∏–∑–æ–≤–∞—Ç—å –º–µ—Ç–æ–¥ Interquartile Range (IQR) (‚òÖ‚òÖ‚òÖ)

–ü–æ—á–∏—Ç–∞—Ç—å –ø—Ä–æ –Ω–µ–≥–æ –º–æ–∂–Ω–æ –ø–æ —Å—Å—ã–ª–∫–µ –≤—ã—à–µ.

In [59]:
s = pd.Series(np.logspace(-2, 2, 30))

print(s)

kek = s.mean()
che = s.std()

FirstQ = kek - .6745*che 
ThirdQ = kek + .6745*che 

IQR = ThirdQ - FirstQ
print('IQR = ', IQR, '\n')

a = FirstQ - 1.5*IQR
b = ThirdQ + 1.5*IQR

print('Boxplot lower whisker: ',a)
print('Boxplot upper whisker: ', b)


for i in range(len(s)):
    if s[i] < a:
        print('Outlier = ', s[i])
    elif s[i] > b:
        print('Outlier = ', s[i])
    else:
        print('Norm')

0       0.010000
1       0.013738
2       0.018874
3       0.025929
4       0.035622
5       0.048939
6       0.067234
7       0.092367
8       0.126896
9       0.174333
10      0.239503
11      0.329034
12      0.452035
13      0.621017
14      0.853168
15      1.172102
16      1.610262
17      2.212216
18      3.039195
19      4.175319
20      5.736153
21      7.880463
22     10.826367
23     14.873521
24     20.433597
25     28.072162
26     38.566204
27     52.983169
28     72.789538
29    100.000000
dtype: float64
IQR =  32.43759572477657

Boxplot lower whisker:  -52.625892795914666
Boxplot upper whisker:  77.12449010319162
Norm
Norm
Norm
Norm
Norm
Norm
Norm
Norm
Norm
Norm
Norm
Norm
Norm
Norm
Norm
Norm
Norm
Norm
Norm
Norm
Norm
Norm
Norm
Norm
Norm
Norm
Norm
Norm
Norm
Outlier =  100.0

36. –ö–∞–∫ –ø–æ–º–µ–Ω—è—Ç—å –º–µ—Å—Ç–∞–º–∏ –¥–≤–µ —Å—Ç—Ä–æ–∫–∏ –¥–∞–Ω–Ω—ã—Ö? (‚òÖ‚òÖ‚òÖ)

In [860]:
df = pd.DataFrame(np.arange(25).reshape(5, -1))

print(df, '\n')

a, b = df.iloc[1, :].copy(), df.iloc[2, :].copy()
df.iloc[1, :], df.iloc[2, :] = b, a

print(df)

    0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

    0   1   2   3   4
0   0   1   2   3   4
1  10  11  12  13  14
2   5   6   7   8   9
3  15  16  17  18  19
4  20  21  22  23  24

### one-hot-encoding

<img src="gifs/one-hot-encoding.png" width="400">

37. –ö–∞–∫ —Å–æ–∑–¥–∞—Ç—å –æ–¥–Ω–æ–∑–Ω–∞—á–Ω—ã–µ –∫–æ–¥–∏—Ä–æ–≤–∫–∏ –∫–∞—Ç–µ–≥–æ—Ä–∏–∞–ª—å–Ω–æ–π –ø–µ—Ä–µ–º–µ–Ω–Ω–æ–π? (‚òÖ‚òÖ‚òÖ)

–°–¥–µ–ª–∞–π—Ç–µ one-hot –∫–æ–¥–∏—Ä–æ–≤–∫—É —Å—Ç–æ–ª–±—Ü–∞ 'a'.

In [55]:
df = pd.DataFrame([['aa', 'kek'], ['ba', 'lol'], ['ab', 'kek'], ['aa', 'lol'], ['cc', 'kek']], columns=['a', 'b'])

print(df)

one_hot = pd.get_dummies(df['a'])

df = df.drop('a',axis = 1)

df = df.join(one_hot)

print(df)

38. –ù–æ—Ä–º–∞–ª–∏–∑—É–π—Ç–µ –≤—Å–µ —Å—Ç–æ–ª–±—Ü—ã –≤ –¥–∞—Ç–∞—Ñ—Ä–µ–π–º–µ. (‚òÖ‚òÖ‚òÖ)

a) –ù–æ—Ä–º–∞–ª–∏–∑–æ–≤–∞—Ç—å –≤—Å–µ —Å—Ç–æ–ª–±—Ü—ã df –ø—É—Ç–µ–º –≤—ã—á–∏—Ç–∞–Ω–∏—è —Å—Ä–µ–¥–Ω–µ–≥–æ –∑–Ω–∞—á–µ–Ω–∏—è —Å—Ç–æ–ª–±—Ü–∞ –∏ –¥–µ–ª–µ–Ω–∏—è –Ω–∞ —Å—Ç–∞–Ω–¥–∞—Ä—Ç–Ω–æ–µ –æ—Ç–∫–ª–æ–Ω–µ–Ω–∏–µ. 

b) –¢—Ä–∞–Ω—Å—Ñ–æ—Ä–º–∏—Ä—É–π—Ç–µ –≤—Å–µ —Å—Ç–æ–ª–±—Ü—ã df —Ç–∞–∫, —á—Ç–æ–±—ã –º–∏–Ω–∏–º–∞–ª—å–Ω–æ–µ –∑–Ω–∞—á–µ–Ω–∏–µ –≤ –∫–∞–∂–¥–æ–º —Å—Ç–æ–ª–±—Ü–µ –±—ã–ª–æ 0, –∞ max = 1.

In [173]:
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

m = df.mean()
sd = df.std()
df = abs((df - m)/sd)
print(df)

          0         1         2         3         4         5         6  \
0  0.172284  0.760674  1.211356  0.111685  0.952030  0.617875  1.130282
1  0.871862  0.672904  1.113468  0.266327  0.168005  0.066062  0.143713
2  1.581881  0.994728  1.040053  0.283509  1.377644  0.431347  1.169123
3  0.036545  1.111755  1.040053  0.953622  0.571218  1.402848  1.200196
4  1.759386  0.292567  1.080839  1.314452  0.571218  0.959844  0.671955
5  0.715240  1.316552  0.191696  1.486276  1.086435  0.244818  1.285647
6  0.130518  0.643648  0.942166  0.850528  1.355243  0.866579  0.112640
7  0.287140  1.228782  0.191696  1.125446  0.705623  1.651553  0.881698

          7         8         9
0  0.636247  0.159907  0.166879
1  0.182364  1.183309  0.634139
2  1.317072  0.242144  2.102672
3  0.571406  0.196457  0.934521
4  1.471068  1.850349  0.901145
5  0.668667  0.561958  0.000000
6  0.757823  0.936596  0.667515
7  1.146865  0.927459  0.133503

In [174]:
df = df.replace(df.max(),1)
df = df.replace(df.min(),0)
df

,0,1,2,3,4,5,6,7,8,9
0,0.172284,0.760674,1.000000,0.000000,0.952030,0.617875,1.130282,0.636247,0.000000,0.166879
1,0.871862,0.672904,1.113468,0.266327,0.000000,0.000000,0.143713,0.000000,1.183309,0.634139
2,1.581881,0.994728,1.040053,0.283509,1.000000,0.431347,1.169123,1.317072,0.242144,1.000000
3,0.000000,1.111755,1.040053,0.953622,0.571218,1.402848,1.200196,0.571406,0.196457,0.934521
4,1.000000,0.000000,1.080839,1.314452,0.571218,0.959844,0.671955,1.000000,1.000000,0.901145
5,0.715240,1.000000,0.000000,1.000000,1.086435,0.244818,1.000000,0.668667,0.561958,0.000000
6,0.130518,0.643648,0.942166,0.850528,1.355243,0.866579,0.000000,0.757823,0.936596,0.667515
7,0.287140,1.228782,0.000000,1.125446,0.705623,1.000000,0.881698,1.146865,0.927459,0.133503

38. –ö–∞–∫ –ø–æ–ª—É—á–∏—Ç—å –∫–æ–Ω–∫—Ä–µ—Ç–Ω—É—é –≥—Ä—É–ø–ø—É –∏–∑ –¥–∞—Ç–∞—Ñ—Ä–µ–π–º–∞ —Å–≥—Ä—É–ø–ø–∏—Ä–æ–≤–∞–Ω–Ω–æ–≥–æ –ø–æ –∫–ª—é—á—É? (‚òÖ‚òÖ‚òÖ)

–°–≥—Ä—É–ø–ø–∏—Ä—É–π—Ç–µ –ø–æ 'name', –∏ –≤—ã–≤–µ–¥–∏—Ç–µ –¥–∞–Ω–Ω—ã–µ –ø–æ –≥—Ä—É–ø–ø–µ 'orange'.

(hint: groupby(), get_group())

In [468]:
df = pd.DataFrame({'name': ['apple', 'banana', 'orange'] * 3,
                   'taste': np.random.rand(9),
                   'price': np.random.randint(0, 15, 9)})

gb = df.groupby(['name'])
gb.get_group('orange')

# –≤–æ—Ç –µ–Ω—Ç–æ —Ç–æ—á–Ω–æ –Ω–µ —Ç—Ä–∏ –∑–≤–µ–∑–¥—ã!

     name     taste  price
2  orange  0.878158     14
5  orange  0.902811     14
8  orange  0.662309     10

39. –ö–∞–∫ –≤—ã—á–∏—Å–ª–∏—Ç—å —Å—Ä–µ–¥–Ω–µ–µ –∑–Ω–∞—á–µ–Ω–∏–µ –ø–æ —Å—Ç–æ–ª–±—Ü—É 'price' –ø–æ –∫–∞–∂–¥–æ–º—É —Ñ—Ä—É–∫—Ç—É –≤ –¥–∞—Ç–∞—Ñ—Ä–µ–π–º–µ –∏ —Å–æ—Ö—Ä–∞–Ω–∏—Ç—å —Å–≥—Ä—É–ø–ø–∏—Ä–æ–≤–∞–Ω–Ω—ã–π —Å—Ç–æ–ª–±–µ—Ü –∫–∞–∫ –¥—Ä—É–≥–æ–π —Å—Ç–æ–ª–±–µ—Ü (–Ω–µ –∏–Ω–¥–µ–∫—Å)? (‚òÖ‚òÖ‚òÖ)

In [61]:
df = pd.DataFrame({'name': ['apple', 'banana', 'orange'] * 3,
                   'taste': np.random.rand(9),
                   'price': np.random.randint(0, 15, 9)})
# print(df, '\n')
df.groupby(['name']).mean()

           taste     price
name
apple   0.379019  8.333333
banana  0.364274  7.666667
orange  0.415138  8.333333

40. –ö–∞–∫ –æ–±—ä–µ–¥–∏–Ω–∏—Ç—å –¥–≤–∞ –¥–∞—Ç–∞—Ñ—Ä–µ–π–º–∞ –ø–æ –¥–≤—É–º —Å—Ç–æ–ª–±—Ü–∞–º, —á—Ç–æ–±—ã –≤ –Ω–∏—Ö –æ—Å—Ç–∞–ª–∏—Å—å —Ç–æ–ª—å–∫–æ –æ–±—â–∏–µ —Å—Ç—Ä–æ–∫–∏?  (‚òÖ‚òÖ‚òÖ)

–°–¥–µ–ª–∞—Ç—å merge –¥–≤—É—Ö –¥–∞—Ç–∞—Ñ—Ä–µ–π–º–æ–≤ –ø–æ –∫–æ–ª–æ–Ω–∫–∞–º ['fruit', 'weight'] –∏ ['pazham', 'kilo'].

(hint: pd.merge https://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html#merge )

In [117]:
df1 = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                    'weight': ['high', 'medium', 'low'] * 3,
                    'price': np.random.randint(0, 15, 9)})

df2 = pd.DataFrame({'pazham': ['apple', 'orange', 'pine'] * 2,
                    'kilo': ['high', 'low'] * 3,
                    'price': np.random.randint(0, 15, 6)})
print(df1, '\n')
print(df2)
new_df = pd.merge(df1, df2,  how = 'inner', left_on = ['fruit','weight'], right_on = ['pazham','kilo'])
print('\n', new_df)

    fruit  weight  price
0   apple    high      3
1  banana  medium     11
2  orange     low      6
3   apple    high     11
4  banana  medium      8
5  orange     low     10
6   apple    high      2
7  banana  medium     12
8  orange     low      1

   pazham  kilo  price
0   apple  high      4
1  orange   low     13
2    pine  high     11
3   apple   low     13
4  orange  high     12
5    pine   low     11

     fruit weight  price_x  pazham  kilo  price_y
0   apple   high        3   apple  high        4
1   apple   high       11   apple  high        4
2   apple   high        2   apple  high        4
3  orange    low        6  orange   low       13
4  orange    low       10  orange   low       13
5  orange    low        1  orange   low       13

41. –ö–∞–∫ —É–¥–∞–ª–∏—Ç—å —Å—Ç—Ä–æ–∫–∏ –∏–∑ –¥–∞—Ç–∞—Ñ—Ä–µ–π–º–∞ –ê, –∫–æ—Ç–æ—Ä—ã–µ –ø—Ä–∏—Å—É—Ç—Å—Ç–≤—É—é—Ç –≤ –¥–∞—Ç–∞—Ñ—Ä–µ–π–º–µ B? (‚òÖ‚òÖ‚òÖ)

In [73]:
df1 = pd.DataFrame({'fruit': ['apple', 'orange', 'banana'] * 3,
                    'weight': ['high', 'medium', 'low'] * 3,
                    'price': np.arange(9)})

df2 = pd.DataFrame({'fruit': ['apple', 'orange', 'pine'] * 2,
                    'weight': ['high', 'medium'] * 3,
                    'price': np.arange(6)})

print(df1, '\n')
print(df2)

df1.drop(df1.merge(df2, how = 'inner').index)

    fruit  weight  price
0   apple    high      0
1  orange  medium      1
2  banana     low      2
3   apple    high      3
4  orange  medium      4
5  banana     low      5
6   apple    high      6
7  orange  medium      7
8  banana     low      8

    fruit  weight  price
0   apple    high      0
1  orange  medium      1
2    pine    high      2
3   apple  medium      3
4  orange    high      4
5    pine  medium      5

    fruit  weight  price
2  banana     low      2
3   apple    high      3
4  orange  medium      4
5  banana     low      5
6   apple    high      6
7  orange  medium      7
8  banana     low      8

42. –ö–∞–∫ –ø–æ–ª—É—á–∏—Ç—å –Ω–æ–º–µ—Ä–∞ —Å—Ç—Ä–æ–∫, –≤ –∫–æ—Ç–æ—Ä—ã—Ö —Å–æ–≤–ø–∞–¥–∞—é—Ç –∑–Ω–∞—á–µ–Ω–∏—è –¥–≤—É—Ö —Å—Ç–æ–ª–±—Ü–æ–≤? (‚òÖ‚òÖ‚òÖ)

(hint: np.where)

In [156]:
df = pd.DataFrame({'fruit1': np.random.choice(['apple', 'orange', 'banana'], 10),
                    'fruit2': np.random.choice(['apple', 'orange', 'banana'], 10)})

print(df, '\n')

df[df['fruit1']==df['fruit2']].index

   fruit1  fruit2
0   apple  orange
1   apple   apple
2  orange   apple
3  banana  orange
4  banana  banana
5   apple  banana
6   apple  orange
7   apple   apple
8  banana  orange
9  banana   apple

Int64Index([1, 4, 7], dtype='int64')

43. –°–æ–∑–¥–∞–π—Ç–µ —Å—Ç–æ–ª–±–µ—Ü a_shift —Å–æ —Å–¥–≤–∏–≥–æ–º –Ω–∞ –æ–¥–Ω—É —Å—Ç—Ä–æ–∫—É –Ω–∞–∑–∞–¥. (‚òÖ‚òÖ‚òÖ)

(hint: .shift())

In [541]:
df = pd.DataFrame(np.random.randint(1, 100, 20).reshape(-1, 4), columns = list('abcd'))

print(df)

df['a_shift'] = ['a_s', 'a_s', 'a_s','a_s','a_s']

print(df)

df.shift(-1, axis = 0)

    a   b   c   d
0  69  11  38  40
1  29  90   9  10
2  77  84  64   9
3  76  72  78  67
4  17  94  40  81
    a   b   c   d a_shift
0  69  11  38  40     a_s
1  29  90   9  10     a_s
2  77  84  64   9     a_s
3  76  72  78  67     a_s
4  17  94  40  81     a_s

      a     b     c     d a_shift
0  29.0  90.0   9.0  10.0     a_s
1  77.0  84.0  64.0   9.0     a_s
2  76.0  72.0  78.0  67.0     a_s
3  17.0  94.0  40.0  81.0     a_s
4   NaN   NaN   NaN   NaN     NaN

44. –ö–∞–∫ —Ä–∞–∑–±–∏—Ç—å —Ç–µ–∫—Å—Ç–æ–≤—ã–π —Å—Ç–æ–ª–±–µ—Ü –Ω–∞ —Ç—Ä–∏ –æ—Ç–¥–µ–ª—å–Ω—ã—Ö —Å—Ç–æ–ª–±—Ü–∞? (‚òÖ‚òÖ‚òÖ)

–†–∞–∑–±–∏—Ç—å –Ω–∞ —Ç—Ä–∏ —Å—Ç–æ–ª–±—Ü—ã STD, City, State

In [699]:
df = pd.DataFrame(["STD, City    State",
"33, Kolkata    West Bengal",
"44, Chennai    Tamil Nadu",
"40, Hyderabad    Telengana",
"80, Bangalore    Karnataka"], columns=['row'])

print(df, '\n')

new_df = df['row'].str.split(',\s+|\s{4}', expand=True)


new_df.columns=['STD','City', 'State']

new_df.drop(0)

                          row
0          STD, City    State
1  33, Kolkata    West Bengal
2   44, Chennai    Tamil Nadu
3  40, Hyderabad    Telengana
4  80, Bangalore    Karnataka

  STD       City        State
1  33    Kolkata  West Bengal
2  44    Chennai   Tamil Nadu
3  40  Hyderabad    Telengana
4  80  Bangalore    Karnataka

## 45. –ù—É –∞ —Ç–µ–ø–µ—Ä—å –≤—Å–µ –≤–º–µ—Å—Ç–µ.  (‚òÖ‚òÖ‚òÖ‚òÖ‚òÖ‚òÖ‚òÖ‚òÖ‚òÖ‚òÖ)

<img src="gifs/remember.gif" width="400">

* –ó–∞–º–µ–Ω—è–µ–º –≤—Å–µ —Ç–æ—á–∫–∏ –≤ –Ω–∞–∑–≤–∞–Ω–∏–∏ –Ω–∞ '_'
* –í—ã–¥–µ–ª–∏—Ç—å –∫–∞—Ç–µ–≥–æ—Ä–∏–∞–ª—å–Ω—ã–µ –ø—Ä–∏–∑–Ω–∞–∫–∏
* –ü–æ—Å—á–∏—Ç–∞—Ç—å –∫–æ–ª-–≤–æ —É–Ω–∏–∫–∞–ª—å–Ω—ã—Ö –∑–Ω–∞—á–µ–Ω–∏–π –≤–æ –≤—Å–µ—Ö —Ç–µ–∫—Å—Ç–æ–≤—ã—Ö\–∫–∞—Ç–µ–≥–æ—Ä–∏–∞–ª—å–Ω—ã—Ö —Å—Ç–æ–ª–±—Ü–∞—Ö. 
* –ö–æ–ª–æ–Ω–∫–∏ —Å —Ç–æ–ª—å–∫–æ —É–Ω–∏–∫–∞–ª—å–Ω—ã–º–∏ –∑–Ω–∞—á–µ–Ω–∏—è–º–∏ —É–¥–∞–ª—è–µ–º (–Ω–∞–ø—Ä–∏–º–µ—Ä Model –∏ Make)
* –î–ª—è —Å—Ç–æ–ª–±—Ü–æ–≤ —É –∫–æ—Ç–æ—Ä—ã—Ö –∑–Ω–∞—á–µ–Ω–∏–π –±–æ–ª–µ–µ 10, –æ—Å—Ç–∞–≤–ª—è–µ–º —Ç–æ–ø 10 –∑–Ω–∞—á–µ–Ω–∏–π, –æ—Å—Ç–∞–ª—å–Ω—ã–µ –∑–∞–º–µ–Ω—è–µ–º –Ω–∞ 'other'
* –ß–∏—Å–ª–æ–≤—ã–µ —Å—Ç–æ–ª–±—Ü—ã –ø—Ä–æ–≤–µ—Ä—è–µ–º –Ω–∞ –ø—Ä–æ–ø—É—Å–∫–∏. –ü–æ–¥—Å—á–∏—Ç—ã–≤–∞–µ–º –∫–æ–ª-–≤–æ nan\none –∏ –¥–µ–ª–∏–º –Ω–∞ —Ä–∞–∑–º–µ—Ä –¥–∞—Ç–∞—Ñ—Ä–µ–π–º–∞ -—Å–æ—Ö—Ä–∞–Ω—è–µ–º –≤ –æ—Ç–¥–µ–ª—å–Ω—ã–π –¥–∞—Ç–∞—Ñ—Ä–µ–π–º, —ç—Ç–æ –¥–æ–ª—è –ø—Ä–æ–ø—É—Å–∫–æ–≤ –≤ –∫–∞–∂–¥–æ–º —Å—Ç–æ–ª–±—Ü–µ
* –ß–∏—Å—Ç–∏–º –≤—ã–±—Ä–æ—Å—ã. –í–æ –≤—Å–µ—Ö —á–∏—Å–ª–æ–≤—ã—Ö —Å—Ç–æ–ª–±—Ü–∞—Ö –∑–∞–º–µ–Ω—è–µ–º –≤—Å–µ –∑–Ω–∞—á–µ–Ω–∏—è —Å—Ç–æ–ª–±—Ü–∞ –º–µ–Ω—å—à–µ 5–≥–æ –ø–µ—Ä—Å–µ–Ω—Ç–∏–ª—è –∏ –±–æ–ª—å—à–µ 95–æ–≥–æ –ø–µ—Ä—Å–µ–Ω—Ç–∏–ª—è –Ω–∞ —ç—Ç–∏ –ø–æ–≥—Ä–∞–Ω–∏—á–Ω—ã–µ –∑–Ω–∞—á–µ–Ω–∏—è.
* –ó–∞–ø–æ–ª–Ω—è–µ–º –ø—Ä–æ–ø—É—Å–∫–∏ –≤ —á–∏—Å–ª–æ–≤—ã—Ö —Å—Ç–æ–ª–±—Ü–∞—Ö –Ω–∞ —Å—Ä–µ–¥–Ω–µ–µ –ø–æ —Å—Ç–æ–ª–±—Ü—É, –≤ —Ç–µ–∫—Å—Ç–æ–≤—ã—Ö —Å—Ç–æ–ª–±—Ü–∞—Ö –Ω–∞ 'other'
* –í—Å–µ –∫–∞—Ç–µ–≥–æ—Ä–∏–∞–ª—å–Ω—ã–µ –ø—Ä–∏–∑–Ω–∞–∫–∏ –ø—Ä–µ–≤—Ä–∞—â–∞–µ–º –≤ one-hot-encoding
* –°–æ–∑–¥–∞—Ç—å –Ω–æ–≤—ã–π —Å—Ç–æ–ª–±–µ—Ü Length_Width = Length * Width
* –°—Ç–æ–ª–±—Ü—ã MPG_city–º–∏ MPG_highway –∏–∑ MPG –ø–µ—Ä–µ–≤–µ—Å—Ç–∏ –≤ –µ–¥–∏–Ω–∏—Ü—ã LPG (–ª–∏—Ç—Ä—ã \100 –∫–º) = (100 * 3,785)  / (MPG * 1,609)
* –ü–æ—Å—á–∏—Ç–∞—Ç—å —Å—Ä–µ–¥–Ω—é—é —Ü–µ–Ω—É –ø–æ –∫–∞–∂–¥–æ–º—É —Ç–∏–ø—É –º–∞—à–∏–Ω—ã —É –∫–∞–∂–¥–æ–≥–æ –ø—Ä–æ–∏–∑–≤–æ–¥–∏—Ç–µ–ª—è
* –ü–æ—Å—á–∏—Ç–∞—Ç—å –º–∞–∫—Å–∏–º–∞–ª—å–Ω—ã–µ Length –∏ Width –ø–æ Type
* –ü–æ—Å—á–∏—Ç–∞—Ç—å –∫–æ–ª-–≤–æ –º–æ–¥–µ–ª–µ–π –º–∞—à–∏–Ω –ø–æ —Ç–∏–ø—É –º–∞—à–∏–Ω—ã –∏ –Ω–∞–ª–∏—á–∏—é –ø–æ–¥—É—à–∫–∏ –±–µ–∑–æ–ø–∞—Å–Ω–æ—Å—Ç–∏ (–∞–≥—Ä–µ–≥–∏—Ä–æ–≤–∞–Ω–∏–µ –ø–æ —Å—Ç–æ–ª–±—Ü–∞–º Type –∏ AirBags)
* –ü–æ—Å—á–∏—Ç–∞—Ç—å –∫–æ–ª-–≤–æ –º–∞—à–∏–Ω –ø–æ –∫–∞–∂–¥–æ–º—É —Ç–∏–ø—É –º–∞—à–∏–Ω—ã —É –∫–∞–∂–¥–æ–≥–æ –ø—Ä–æ–∏–∑–≤–æ–¥–∏—Ç–µ–ª—è(–∞–≥—Ä–µ–≥–∏—Ä–æ–≤–∞–Ω–∏–µ –ø–æ —Å—Ç–æ–ª–±—Ü–∞–º Type –∏ Manufacturer)
* –ü–æ—Å—á–∏—Ç–∞—Ç—å –∫–æ–ª-–≤–æ –º–∞—à–∏–Ω –ø–æ Manufacturer-Man_trans_avail
* –í—ã–≤–µ—Å—Ç–∏ —É –∫–∞–∫–æ–π –º–æ–¥–µ–ª–∏, –∫–∞–∫–æ–≥–æ –∏–∑–≥–æ—Ç–æ–≤–∏—Ç–µ–ª—è –º–∞–∫—Å–∏–º–∞–ª—å–Ω–∞—è –≤–º–µ—Å—Ç–∏–º–æ—Å—Ç—å –ø–æ –ø–∞—Å—Å–∞–∂–∏—Ä–∞–º

In [621]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

#1 –ó–∞–º–µ–Ω—è–µ–º –≤—Å–µ —Ç–æ—á–∫–∏ –≤ –Ω–∞–∑–≤–∞–Ω–∏–∏ –Ω–∞ '_'

df.columns = [col.replace('.', '_') for col in df.columns]

df

,Manufacturer,Model,Type,Min_Price,Price,Max_Price,MPG_city,MPG_highway,AirBags,DriveTrain,...,Passengers,Length,Wheelbase,Width,Turn_circle,Rear_seat_room,Luggage_room,Weight,Origin,Make
0,Acura,Integra,Small,12.9,15.9,18.8,25.0,31.0,None,Front,...,5.0,177.0,102.0,68.0,37.0,26.5,NaN,2705.0,non-USA,Acura Integra
1,NaN,Legend,Midsize,29.2,33.9,38.7,18.0,25.0,Driver & Passenger,Front,...,5.0,195.0,115.0,71.0,38.0,30.0,15.0,3560.0,non-USA,Acura Legend
2,Audi,90,Compact,25.9,29.1,32.3,20.0,26.0,Driver only,Front,...,5.0,180.0,102.0,67.0,37.0,28.0,14.0,3375.0,non-USA,Audi 90
3,Audi,100,Midsize,NaN,37.7,44.6,19.0,26.0,Driver & Passenger,NaN,...,6.0,193.0,106.0,NaN,37.0,31.0,17.0,3405.0,non-USA,Audi 100
4,BMW,535i,Midsize,NaN,30.0,NaN,22.0,30.0,NaN,Rear,...,4.0,186.0,109.0,69.0,39.0,27.0,13.0,3640.0,non-USA,BMW 535i
5,Buick,Century,Midsize,14.2,15.7,17.3,22.0,31.0,Driver only,NaN,...,6.0,189.0,105.0,69.0,41.0,28.0,16.0,NaN,USA,Buick Century
6,Buick,LeSabre,Large,19.9,20.8,NaN,19.0,28.0,Driver only,Front,...,6.0,200.0,111.0,74.0,42.0,30.5,17.0,3470.0,USA,Buick LeSabre
7,Buick,Roadmaster,Large,22.6,23.7,24.9,16.0,25.0,Driver only,Rear,...,6.0,216.0,116.0,78.0,45.0,30.5,21.0,4105.0,USA,Buick Roadmaster
8,Buick,Riviera,Midsize,26.3,26.3,26.3,19.0,27.0,Driver only,Front,...,5.0,198.0,108.0,NaN,41.0,26.5,14.0,3495.0,USA,Buick Riviera
9,Cadillac,DeVille,Large,33.0,34.7,36.3,16.0,25.0,Driver only,Front,...,6.0,206.0,114.0,73.0,43.0,35.0,18.0,3620.0,USA,Cadillac DeVille
10,Cadillac,Seville,Midsize,37.5,40.1,42.7,16.0,25.0,Driver & Passenger,Front,...,5.0,204.0,111.0,74.0,44.0,31.0,NaN,3935.0,USA,Cadillac Seville
11,Chevrolet,Cavalier,Compact,8.5,13.4,18.3,25.0,36.0,NaN,NaN,...,5.0,182.0,101.0,66.0,38.0,25.0,13.0,2490.0,USA,Chevrolet Cavalier
12,Chevrolet,Corsica,Compact,11.4,11.4,11.4,25.0,34.0,Driver only,Front,...,5.0,184.0,103.0,68.0,39.0,26.0,NaN,2785.0,USA,Chevrolet Corsica
13,Chevrolet,Camaro,Sporty,13.4,15.1,16.8,19.0,28.0,Driver & Passenger,Rear,...,4.0,193.0,101.0,74.0,43.0,25.0,13.0,3240.0,USA,Chevrolet Camaro
14,Chevrolet,Lumina,Midsize,13.4,15.9,18.4,NaN,29.0,None,Front,...,6.0,NaN,108.0,71.0,NaN,28.5,16.0,3195.0,USA,Chevrolet Lumina
15,Chevrolet,Lumina_APV,Van,14.7,16.3,18.0,18.0,23.0,None,Front,...,7.0,178.0,110.0,74.0,44.0,30.5,NaN,3715.0,USA,Chevrolet Lumina_APV
16,Chevrolet,Astro,Van,14.7,16.6,18.6,15.0,20.0,None,4WD,...,8.0,194.0,111.0,78.0,42.0,33.5,NaN,4025.0,USA,Chevrolet Astro
17,Chevrolet,Caprice,Large,18.0,18.8,19.6,17.0,26.0,Driver only,Rear,...,6.0,214.0,116.0,77.0,42.0,29.5,20.0,3910.0,USA,Chevrolet Caprice
18,Chevrolet,Corvette,Sporty,34.6,38.0,41.5,17.0,25.0,Driver only,Rear,...,2.0,179.0,96.0,74.0,43.0,NaN,NaN,3380.0,NaN,Chevrolet Corvette
19,NaN,Concorde,Large,18.4,18.4,18.4,20.0,28.0,Driver & Passenger,Front,...,6.0,203.0,113.0,74.0,NaN,31.0,15.0,3515.0,USA,Chrylser Concorde
20,Chrysler,LeBaron,Compact,14.5,15.8,17.1,23.0,28.0,Driver & Passenger,Front,...,6.0,183.0,104.0,68.0,41.0,30.5,14.0,3085.0,USA,Chrysler LeBaron
21,Chrysler,Imperial,Large,29.5,29.5,29.5,20.0,26.0,Driver only,Front,...,6.0,203.0,110.0,69.0,44.0,36.0,17.0,3570.0,USA,Chrysler Imperial
22,Dodge,Colt,Small,7.9,9.2,10.6,29.0,33.0,None,Front,...,5.0,174.0,98.0,66.0,32.0,NaN,11.0,2270.0,USA,Dodge Colt
23,Dodge,Shadow,Small,8.4,11.3,14.2,23.0,29.0,Driver only,Front,...,5.0,172.0,97.0,67.0,38.0,26.5,NaN,2670.0,USA,Dodge Shadow
24,Dodge,Spirit,Compact,11.9,13.3,14.7,22.0,27.0,Driver only,Front,...,6.0,181.0,104.0,68.0,39.0,30.5,NaN,2970.0,USA,Dodge Spirit
25,Dodge,Caravan,Van,NaN,19.0,24.4,17.0,21.0,Driver only,4WD,...,7.0,175.0,112.0,72.0,42.0,26.5,NaN,3705.0,USA,Dodge Caravan
26,Dodge,Dynasty,Midsize,14.8,15.6,16.4,21.0,NaN,Driver only,Front,...,6.0,192.0,105.0,69.0,42.0,30.5,16.0,3080.0,USA,Dodge Dynasty
27,Dodge,Stealth,Sporty,18.5,25.8,33.1,NaN,24.0,Driver only,4WD,...,4.0,180.0,97.0,NaN,40.0,20.0,11.0,3805.0,USA,Dodge Stealth
28,Eagle,Summit,Small,7.9,12.2,16.5,29.0,33.0,None,Front,...,5.0,174.0,98.0,66.0,36.0,26.5,11.0,2295.0,USA,Eagle Summit
29,Eagle,Vision,Large,NaN,19.3,21.2,20.0,28.0,Driver & Passenger,Front,...,6.0,202.0,113.0,74.0,40.0,30.0,15.0,3490.0,USA,Eagle Vision
30,Ford,Festiva,Small,6.9,7.4,7.9,31.0,33.0,NaN,Front,...,4.0,141.0,90.0,63.0,33.0,26.0,12.0,1845.0,USA,Ford Festiva
31,Ford,Escort,Small,8.4,10.1,11.9,23.0,30.0,None,Front,...,5.0,171.0,98.0,67.0,36.0,28.0,12.0,2530.0,USA,Ford Escort
32,Ford,Tempo,Compact,10.4,11.3,12.2,22.0,27.0,None,Front,...,5.0,177.0,100.0,68.0,NaN,27.5,13.0,NaN,USA,NaN
33,Ford,Mustang,Sporty,10.8,15.9,21.0,22.0,29.0,Driver only,Rear,...,4.0,180.0,101.0,68.0,40.0,24.0,12.0,NaN,USA,Ford Mustang
34,Ford,Probe,Sporty,12.8,14.0,15.2,NaN,30.0,Driver only,Front,...,4.0,179.0,103.0,70.0,38.0,23.0,18.0,2710.0,USA,Ford Probe
35,Ford,Aerostar,Van,14.5,19.9,25.3,15.0,20.0,Driver only,4WD,...,7.0,176.0,119.0,72.0,45.0,30.0,NaN,3735.0,USA,Ford Aerostar
36,Ford,Taurus,Midsize,15.6,20.2,24.8,21.0,30.0,Driver only,Front,...,5.0,192.0,106.0,71.0,40.0,27.5,18.0,3325.0,USA,Ford Taurus
37,Ford,Crown_Victoria,Large,20.1,20.9,21.7,18.0,26.0,Driver only,Rear,...,6.0,212.0,114.0,78.0,43.0,30.0,21.0,3950.0,USA,Ford Crown_Victoria
38,Geo,Metro,Small,6.7,8.4,10.0,46.0,50.0,None,Front,...,4.0,151.0,93.0,63.0,34.0,27.5,10.0,1695.0,non-USA,Geo Metro
39,Geo,Storm,Sporty,11.5,12.5,13.5,30.0,36.0,Driver only,Front,...,4.0,164.0,97.0,NaN,37.0,24.5,11.0,2475.0,non-USA,Geo Storm
40,Honda,Prelude,Sporty,17.0,19.8,22.7,24.0,31.0,Driver & Passenger,Front,...,4.0,175.0,100.0,70.0,39.0,23.5,8.0,2865.0,non-USA,Honda Prelude
41,Honda,Civic,Small,8.4,12.1,15.8,42.0,46.0,Driver only,Front,...,4.0,173.0,NaN,67.0,36.0,28.0,12.0,NaN,non-USA,Honda Civic
42,Honda,Accord,Compact,13.8,17.5,21.2,24.0,31.0,Driver & Passenger,Front,...,4.0,185.0,107.0,67.0,41.0,28.0,14.0,3040.0,non-USA,Honda Accord
43,Hyundai,Excel,Small,6.8,8.0,9.2,29.0,33.0,None,Front,...,5.0,168.0,94.0,63.0,35.0,26.0,11.0,2345.0,non-USA,Hyundai Excel
44,Hyundai,Elantra,Small,9.0,10.0,11.0,NaN,29.0,None,Front,...,5.0,172.0,98.0,66.0,36.0,28.0,12.0,2620.0,non-USA,Hyundai Elantra
45,Hyundai,Scoupe,NaN,9.1,10.0,11.0,26.0,34.0,None,Front,...,4.0,166.0,94.0,64.0,34.0,23.5,9.0,2285.0,non-USA,NaN
46,Hyundai,Sonata,Midsize,12.4,13.9,15.3,20.0,27.0,None,Front,...,5.0,184.0,104.0,69.0,41.0,31.0,NaN,2885.0,NaN,Hyundai Sonata
47,Infiniti,Q45,Midsize,45.4,47.9,NaN,17.0,22.0,NaN,Rear,...,5.0,200.0,113.0,72.0,42.0,29.0,15.0,4000.0,non-USA,Infiniti Q45
48,Lexus,ES300,Midsize,27.5,28.0,28.4,18.0,24.0,Driver only,Front,...,5.0,188.0,103.0,70.0,40.0,27.5,14.0,3510.0,non-USA,Lexus ES300
49,NaN,SC300,Midsize,34.7,35.2,35.6,18.0,23.0,Driver & Passenger,Rear,...,4.0,191.0,106.0,71.0,39.0,25.0,9.0,3515.0,non-USA,Lexus SC300
50,Lincoln,Continental,Midsize,33.3,34.3,35.3,17.0,26.0,Driver & Passenger,NaN,...,6.0,205.0,109.0,73.0,42.0,30.0,19.0,3695.0,USA,Lincoln Continental
51,Lincoln,Town_Car,Large,34.4,36.1,37.8,18.0,26.0,Driver & Passenger,Rear,...,NaN,219.0,117.0,77.0,45.0,31.5,22.0,4055.0,USA,Lincoln Town_Car
52,Mazda,323,Small,7.4,8.3,9.1,29.0,37.0,None,Front,...,4.0,164.0,97.0,66.0,34.0,27.0,16.0,2325.0,non-USA,Mazda 323
53,Mazda,Protege,Small,10.9,11.6,12.3,28.0,36.0,None,Front,...,5.0,172.0,98.0,66.0,36.0,26.5,13.0,2440.0,non-USA,Mazda Protege
54,Mazda,626,Compact,14.3,16.5,18.7,26.0,34.0,Driver only,Front,...,5.0,184.0,103.0,69.0,40.0,29.5,14.0,2970.0,non-USA,Mazda 626
55,Mazda,MPV,Van,16.6,19.1,21.7,18.0,24.0,None,4WD,...,7.0,190.0,110.0,72.0,39.0,27.5,NaN,3735.0,non-USA,Mazda MPV
56,Mazda,RX-7,Sporty,32.5,32.5,32.5,17.0,25.0,Driver only,NaN,...,2.0,169.0,96.0,69.0,NaN,NaN,NaN,NaN,non-USA,Mazda RX-7
57,Mercedes-Benz,190E,Compact,29.0,31.9,34.9,NaN,29.0,Driver only,Rear,...,5.0,175.0,105.0,67.0,34.0,26.0,12.0,2920.0,NaN,Mercedes-Benz 190E
58,Mercedes-Benz,300E,Midsize,43.8,61.9,80.0,19.0,25.0,Driver & Passenger,Rear,...,5.0,NaN,110.0,69.0,37.0,NaN,15.0,3525.0,non-USA,Mercedes-Benz 300E
59,Mercury,NaN,Sporty,13.3,14.1,15.0,23.0,26.0,Driver only,Front,...,4.0,166.0,95.0,65.0,36.0,19.0,6.0,2450.0,USA,Mercury Capri
60,Mercury,Cougar,Midsize,14.9,14.9,14.9,19.0,26.0,None,Rear,...,5.0,199.0,113.0,73.0,38.0,28.0,15.0,3610.0,USA,Mercury Cougar
61,Mitsubishi,Mirage,Small,7.7,10.3,12.9,29.0,NaN,None,Front,...,5.0,172.0,98.0,67.0,36.0,26.0,11.0,2295.0,non-USA,Mitsubishi Mirage
62,Mitsubishi,Diamante,Midsize,22.4,26.1,NaN,18.0,24.0,Driver only,Front,...,5.0,190.0,107.0,70.0,43.0,27.5,14.0,3730.0,non-USA,Mitsubishi Diamante
63,Nissan,Sentra,Small,8.7,11.8,14.9,29.0,33.0,Driver only,Front,...,5.0,170.0,96.0,66.0,33.0,26.0,NaN,NaN,non-USA,Nissan Sentra
64,Nissan,Altima,Compact,13.0,15.7,18.3,24.0,30.0,Driver only,Front,...,5.0,181.0,103.0,67.0,40.0,28.5,14.0,3050.0,non-USA,Nissan Altima
65,Nissan,Quest,Van,16.7,19.1,21.5,17.0,23.0,None,Front,...,7.0,190.0,112.0,74.0,41.0,27.0,NaN,4100.0,non-USA,Nissan Quest
66,Nissan,Maxima,Midsize,21.0,21.5,22.0,21.0,26.0,Driver only,Front,...,5.0,188.0,104.0,69.0,41.0,28.5,14.0,3200.0,non-USA,Nissan Maxima
67,Oldsmobile,Achieva,Compact,13.0,13.5,14.0,24.0,31.0,None,Front,...,5.0,188.0,103.0,67.0,39.0,28.0,14.0,2910.0,USA,Oldsmobile Achieva
68,Oldsmobile,Cutlass_Ciera,Midsize,14.2,16.3,18.4,23.0,31.0,Driver only,Front,...,5.0,190.0,105.0,70.0,42.0,28.0,16.0,2890.0,USA,Oldsmobile Cutlass_Ciera
69,Oldsmobile,Silhouette,Van,19.5,19.5,19.5,18.0,23.0,None,Front,...,7.0,NaN,110.0,74.0,44.0,30.5,NaN,3715.0,USA,Oldsmobile Silhouette
70,Oldsmobile,Eighty-Eight,Large,19.5,20.7,21.9,NaN,28.0,Driver only,Front,...,6.0,201.0,111.0,74.0,42.0,31.5,17.0,3470.0,USA,Oldsmobile Eighty-Eight
71,Plymouth,Laser,Sporty,11.4,14.4,17.4,NaN,30.0,None,4WD,...,4.0,173.0,97.0,67.0,39.0,24.5,8.0,2640.0,NaN,Plymouth Laser
72,Pontiac,LeMans,Small,NaN,9.0,9.9,31.0,41.0,None,Front,...,4.0,177.0,99.0,66.0,35.0,25.5,17.0,2350.0,USA,Pontiac LeMans
73,Pontiac,Sunbird,Compact,9.4,11.1,12.8,NaN,31.0,None,NaN,...,5.0,181.0,101.0,66.0,39.0,25.0,13.0,NaN,USA,NaN
74,Pontiac,Firebird,NaN,14.0,17.7,21.4,19.0,28.0,Driver & Passenger,Rear,...,4.0,196.0,101.0,75.0,43.0,25.0,13.0,3240.0,USA,Pontiac Firebird
75,Pontiac,Grand_Prix,Midsize,15.4,18.5,21.6,19.0,27.0,None,Front,...,5.0,195.0,108.0,72.0,41.0,28.5,16.0,3450.0,USA,Pontiac Grand_Prix
76,Pontiac,Bonneville,Large,19.4,24.4,29.4,19.0,28.0,Driver & Passenger,Front,...,6.0,177.0,111.0,74.0,43.0,30.5,18.0,3495.0,USA,Pontiac Bonneville
77,Saab,900,Compact,20.3,28.7,37.1,20.0,26.0,NaN,Front,...,5.0,NaN,99.0,67.0,37.0,26.5,14.0,2775.0,non-USA,Saab 900
78,Saturn,SL,Small,9.2,NaN,12.9,NaN,38.0,Driver only,Front,...,5.0,176.0,102.0,68.0,40.0,26.5,NaN,2495.0,USA,Saturn SL
79,Subaru,Justy,Small,7.3,8.4,9.5,33.0,37.0,None,4WD,...,4.0,146.0,90.0,60.0,32.0,23.5,10.0,2045.0,non-USA,Subaru Justy
80,Subaru,Loyale,Small,10.5,10.9,11.3,25.0,30.0,None,4WD,...,5.0,175.0,97.0,65.0,35.0,27.5,15.0,2490.0,non-USA,Subaru Loyale
81,Subaru,Legacy,Compact,16.3,19.5,22.7,23.0,30.0,Driver only,4WD,...,5.0,179.0,102.0,67.0,37.0,27.0,14.0,3085.0,non-USA,Subaru Legacy
82,Suzuki,Swift,NaN,7.3,8.6,NaN,39.0,43.0,None,Front,...,4.0,161.0,93.0,NaN,34.0,27.5,10.0,1965.0,non-USA,Suzuki Swift
83,Toyota,Tercel,Small,NaN,9.8,11.8,32.0,37.0,Driver only,Front,...,NaN,162.0,94.0,NaN,36.0,24.0,11.0,2055.0,non-USA,Toyota Tercel
84,Toyota,Celica,Sporty,14.2,18.4,22.6,25.0,32.0,NaN,Front,...,4.0,174.0,99.0,69.0,NaN,23.0,13.0,2950.0,non-USA,Toyota Celica
85,Toyota,Camry,Midsize,15.2,NaN,21.2,22.0,29.0,Driver only,NaN,...,5.0,188.0,103.0,70.0,38.0,28.5,15.0,3030.0,non-USA,Toyota Camry
86,Toyota,Previa,Van,NaN,22.7,26.6,18.0,22.0,Driver only,4WD,...,7.0,187.0,113.0,71.0,41.0,35.0,NaN,3785.0,non-USA,Toyota Previa
87,Volkswagen,Fox,Small,8.7,9.1,9.5,25.0,33.0,None,Front,...,4.0,163.0,93.0,63.0,34.0,26.0,10.0,2240.0,non-USA,Volkswagen Fox
88,Volkswagen,Eurovan,Van,16.6,19.7,22.7,17.0,21.0,None,Front,...,7.0,187.0,115.0,72.0,38.0,34.0,NaN,3960.0,NaN,Volkswagen Eurovan
89,Volkswagen,Passat,Compact,17.6,20.0,22.4,21.0,30.0,None,Front,...,5.0,180.0,103.0,67.0,35.0,31.5,14.0,2985.0,non-USA,Volkswagen Passat
90,Volkswagen,Corrado,Sporty,22.9,23.3,23.7,18.0,25.0,None,Front,...,4.0,159.0,97.0,66.0,36.0,26.0,15.0,2810.0,non-USA,Volkswagen Corrado
91,Volvo,240,Compact,21.8,22.7,23.5,21.0,28.0,Driver only,Rear,...,5.0,190.0,104.0,67.0,37.0,29.5,14.0,2985.0,non-USA,Volvo 240
92,NaN,850,Midsize,24.8,26.7,28.5,20.0,28.0,Driver & Passenger,Front,...,5.0,184.0,105.0,69.0,38.0,30.0,15.0,3245.0,non-USA,Volvo 850

In [622]:
#2 –í—ã–¥–µ–ª–∏—Ç—å –∫–∞—Ç–µ–≥–æ—Ä–∏–∞–ª—å–Ω—ã–µ –ø—Ä–∏–∑–Ω–∞–∫–∏

text_columns =  df.select_dtypes(include = ['object']) 
numeric_columns =  df.select_dtypes(exclude = ['object']) 

print(text_columns.describe())
print()
print(numeric_columns.describe())

       Manufacturer    Model     Type      AirBags DriveTrain Cylinders  \
count            89       92       90           87         86        88
unique           31       92        6            3          3         6
top       Chevrolet  Seville  Midsize  Driver only      Front         4
freq              8        1       22           39         61        45

       Man_trans_avail Origin               Make
count               88     88                 90
unique               2      2                 90
top                Yes    USA  Chevrolet Corsica
freq                57     46                  1

       Min_Price      Price  Max_Price   MPG_city  MPG_highway  EngineSize  \
count  86.000000  91.000000  88.000000  84.000000    91.000000   91.000000
mean   17.118605  19.616484  21.459091  22.404762    29.065934    2.658242
std     8.828290   9.724280  10.696563   5.841520     5.370293    1.045845
min     6.700000   7.400000   7.900000  15.000000    20.000000    1.000000
25%    10.825000  12.350000  14.575000  18.000000    26.000000    1.800000
50%    14.600000  17.700000  19.150000  21.000000    28.000000    2.300000
75%    20.250000  23.500000  24.825000  25.000000    31.000000    3.250000
max    45.400000  61.900000  80.000000  46.000000    50.000000    5.700000

       Horsepower          RPM  Rev_per_mile  Fuel_tank_capacity  Passengers  \
count   86.000000    90.000000     87.000000           85.000000   91.000000
mean   144.000000  5276.666667   2355.000000           16.683529    5.076923
std     53.455204   605.554811    486.916616            3.375748    1.045953
min     55.000000  3800.000000   1320.000000            9.200000    2.000000
25%    100.750000  4800.000000   2017.500000           14.500000    4.000000
50%    140.000000  5200.000000   2360.000000           16.500000    5.000000
75%    170.000000  5787.500000   2565.000000           19.000000    6.000000
max    300.000000  6500.000000   3755.000000           27.000000    8.000000

           Length   Wheelbase      Width  Turn_circle  Rear_seat_room  \
count   89.000000   92.000000  87.000000    88.000000       89.000000
mean   182.865169  103.956522  69.448276    38.954545       27.853933
std     14.792651    6.856317   3.778023     3.304157        3.018129
min    141.000000   90.000000  60.000000    32.000000       19.000000
25%    174.000000   98.000000  67.000000    36.000000       26.000000
50%    181.000000  103.000000  69.000000    39.000000       27.500000
75%    192.000000  110.000000  72.000000    42.000000       30.000000
max    219.000000  119.000000  78.000000    45.000000       36.000000

       Luggage_room       Weight
count     74.000000    86.000000
mean      13.986486  3104.593023
std        3.120824   600.129993
min        6.000000  1695.000000
25%       12.000000  2647.500000
50%       14.000000  3085.000000
75%       16.000000  3567.500000
max       22.000000  4105.000000

In [623]:
#3 –ü–æ—Å—á–∏—Ç–∞—Ç—å –∫–æ–ª-–≤–æ —É–Ω–∏–∫–∞–ª—å–Ω—ã—Ö –∑–Ω–∞—á–µ–Ω–∏–π –≤–æ –≤—Å–µ—Ö —Ç–µ–∫—Å—Ç–æ–≤—ã—Ö\–∫–∞—Ç–µ–≥–æ—Ä–∏–∞–ª—å–Ω—ã—Ö —Å—Ç–æ–ª–±—Ü–∞—Ö.

for i in numeric_columns:
    print(i, df[i].nunique())
print()
for i in text_columns:
    print(i, df[i].nunique())

Min_Price 72
Price 80
Max_Price 76
MPG_city 21
MPG_highway 22
EngineSize 26
Horsepower 53
RPM 24
Rev_per_mile 74
Fuel_tank_capacity 37
Passengers 6
Length 51
Wheelbase 27
Width 16
Turn_circle 14
Rear_seat_room 24
Luggage_room 16
Weight 75

Manufacturer 31
Model 92
Type 6
AirBags 3
DriveTrain 3
Cylinders 6
Man_trans_avail 2
Origin 2
Make 90

In [624]:
#4 –ö–æ–ª–æ–Ω–∫–∏ —Å —Ç–æ–ª—å–∫–æ —É–Ω–∏–∫–∞–ª—å–Ω—ã–º–∏ –∑–Ω–∞—á–µ–Ω–∏—è–º–∏ —É–¥–∞–ª—è–µ–º (–Ω–∞–ø—Ä–∏–º–µ—Ä Model –∏ Make)
for i in text_columns:
    if df[i].count() == df[i].nunique():
        df = df.drop([i], axis = 1)
df

,Manufacturer,Type,Min_Price,Price,Max_Price,MPG_city,MPG_highway,AirBags,DriveTrain,Cylinders,...,Fuel_tank_capacity,Passengers,Length,Wheelbase,Width,Turn_circle,Rear_seat_room,Luggage_room,Weight,Origin
0,Acura,Small,12.9,15.9,18.8,25.0,31.0,None,Front,4,...,13.2,5.0,177.0,102.0,68.0,37.0,26.5,NaN,2705.0,non-USA
1,NaN,Midsize,29.2,33.9,38.7,18.0,25.0,Driver & Passenger,Front,6,...,18.0,5.0,195.0,115.0,71.0,38.0,30.0,15.0,3560.0,non-USA
2,Audi,Compact,25.9,29.1,32.3,20.0,26.0,Driver only,Front,6,...,16.9,5.0,180.0,102.0,67.0,37.0,28.0,14.0,3375.0,non-USA
3,Audi,Midsize,NaN,37.7,44.6,19.0,26.0,Driver & Passenger,NaN,6,...,21.1,6.0,193.0,106.0,NaN,37.0,31.0,17.0,3405.0,non-USA
4,BMW,Midsize,NaN,30.0,NaN,22.0,30.0,NaN,Rear,4,...,21.1,4.0,186.0,109.0,69.0,39.0,27.0,13.0,3640.0,non-USA
5,Buick,Midsize,14.2,15.7,17.3,22.0,31.0,Driver only,NaN,4,...,16.4,6.0,189.0,105.0,69.0,41.0,28.0,16.0,NaN,USA
6,Buick,Large,19.9,20.8,NaN,19.0,28.0,Driver only,Front,6,...,NaN,6.0,200.0,111.0,74.0,42.0,30.5,17.0,3470.0,USA
7,Buick,Large,22.6,23.7,24.9,16.0,25.0,Driver only,Rear,6,...,23.0,6.0,216.0,116.0,78.0,45.0,30.5,21.0,4105.0,USA
8,Buick,Midsize,26.3,26.3,26.3,19.0,27.0,Driver only,Front,6,...,18.8,5.0,198.0,108.0,NaN,41.0,26.5,14.0,3495.0,USA
9,Cadillac,Large,33.0,34.7,36.3,16.0,25.0,Driver only,Front,8,...,18.0,6.0,206.0,114.0,73.0,43.0,35.0,18.0,3620.0,USA
10,Cadillac,Midsize,37.5,40.1,42.7,16.0,25.0,Driver & Passenger,Front,8,...,20.0,5.0,204.0,111.0,74.0,44.0,31.0,NaN,3935.0,USA
11,Chevrolet,Compact,8.5,13.4,18.3,25.0,36.0,NaN,NaN,4,...,15.2,5.0,182.0,101.0,66.0,38.0,25.0,13.0,2490.0,USA
12,Chevrolet,Compact,11.4,11.4,11.4,25.0,34.0,Driver only,Front,NaN,...,15.6,5.0,184.0,103.0,68.0,39.0,26.0,NaN,2785.0,USA
13,Chevrolet,Sporty,13.4,15.1,16.8,19.0,28.0,Driver & Passenger,Rear,NaN,...,NaN,4.0,193.0,101.0,74.0,43.0,25.0,13.0,3240.0,USA
14,Chevrolet,Midsize,13.4,15.9,18.4,NaN,29.0,None,Front,4,...,16.5,6.0,NaN,108.0,71.0,NaN,28.5,16.0,3195.0,USA
15,Chevrolet,Van,14.7,16.3,18.0,18.0,23.0,None,Front,6,...,20.0,7.0,178.0,110.0,74.0,44.0,30.5,NaN,3715.0,USA
16,Chevrolet,Van,14.7,16.6,18.6,15.0,20.0,None,4WD,6,...,27.0,8.0,194.0,111.0,78.0,42.0,33.5,NaN,4025.0,USA
17,Chevrolet,Large,18.0,18.8,19.6,17.0,26.0,Driver only,Rear,8,...,23.0,6.0,214.0,116.0,77.0,42.0,29.5,20.0,3910.0,USA
18,Chevrolet,Sporty,34.6,38.0,41.5,17.0,25.0,Driver only,Rear,8,...,20.0,2.0,179.0,96.0,74.0,43.0,NaN,NaN,3380.0,NaN
19,NaN,Large,18.4,18.4,18.4,20.0,28.0,Driver & Passenger,Front,6,...,18.0,6.0,203.0,113.0,74.0,NaN,31.0,15.0,3515.0,USA
20,Chrysler,Compact,14.5,15.8,17.1,23.0,28.0,Driver & Passenger,Front,4,...,16.0,6.0,183.0,104.0,68.0,41.0,30.5,14.0,3085.0,USA
21,Chrysler,Large,29.5,29.5,29.5,20.0,26.0,Driver only,Front,6,...,16.0,6.0,203.0,110.0,69.0,44.0,36.0,17.0,3570.0,USA
22,Dodge,Small,7.9,9.2,10.6,29.0,33.0,None,Front,4,...,NaN,5.0,174.0,98.0,66.0,32.0,NaN,11.0,2270.0,USA
23,Dodge,Small,8.4,11.3,14.2,23.0,29.0,Driver only,Front,4,...,14.0,5.0,172.0,97.0,67.0,38.0,26.5,NaN,2670.0,USA
24,Dodge,Compact,11.9,13.3,14.7,22.0,27.0,Driver only,Front,4,...,NaN,6.0,181.0,104.0,68.0,39.0,30.5,NaN,2970.0,USA
25,Dodge,Van,NaN,19.0,24.4,17.0,21.0,Driver only,4WD,6,...,20.0,7.0,175.0,112.0,72.0,42.0,26.5,NaN,3705.0,USA
26,Dodge,Midsize,14.8,15.6,16.4,21.0,NaN,Driver only,Front,NaN,...,16.0,6.0,192.0,105.0,69.0,42.0,30.5,16.0,3080.0,USA
27,Dodge,Sporty,18.5,25.8,33.1,NaN,24.0,Driver only,4WD,6,...,19.8,4.0,180.0,97.0,NaN,40.0,20.0,11.0,3805.0,USA
28,Eagle,Small,7.9,12.2,16.5,29.0,33.0,None,Front,4,...,13.2,5.0,174.0,98.0,66.0,36.0,26.5,11.0,2295.0,USA
29,Eagle,Large,NaN,19.3,21.2,20.0,28.0,Driver & Passenger,Front,6,...,18.0,6.0,202.0,113.0,74.0,40.0,30.0,15.0,3490.0,USA
30,Ford,Small,6.9,7.4,7.9,31.0,33.0,NaN,Front,4,...,10.0,4.0,141.0,90.0,63.0,33.0,26.0,12.0,1845.0,USA
31,Ford,Small,8.4,10.1,11.9,23.0,30.0,None,Front,4,...,13.2,5.0,171.0,98.0,67.0,36.0,28.0,12.0,2530.0,USA
32,Ford,Compact,10.4,11.3,12.2,22.0,27.0,None,Front,4,...,15.9,5.0,177.0,100.0,68.0,NaN,27.5,13.0,NaN,USA
33,Ford,Sporty,10.8,15.9,21.0,22.0,29.0,Driver only,Rear,4,...,15.4,4.0,180.0,101.0,68.0,40.0,24.0,12.0,NaN,USA
34,Ford,Sporty,12.8,14.0,15.2,NaN,30.0,Driver only,Front,4,...,15.5,4.0,179.0,103.0,70.0,38.0,23.0,18.0,2710.0,USA
35,Ford,Van,14.5,19.9,25.3,15.0,20.0,Driver only,4WD,6,...,21.0,7.0,176.0,119.0,72.0,45.0,30.0,NaN,3735.0,USA
36,Ford,Midsize,15.6,20.2,24.8,21.0,30.0,Driver only,Front,6,...,NaN,5.0,192.0,106.0,71.0,40.0,27.5,18.0,3325.0,USA
37,Ford,Large,20.1,20.9,21.7,18.0,26.0,Driver only,Rear,8,...,20.0,6.0,212.0,114.0,78.0,43.0,30.0,21.0,3950.0,USA
38,Geo,Small,6.7,8.4,10.0,46.0,50.0,None,Front,3,...,10.6,4.0,151.0,93.0,63.0,34.0,27.5,10.0,1695.0,non-USA
39,Geo,Sporty,11.5,12.5,13.5,30.0,36.0,Driver only,Front,4,...,12.4,4.0,164.0,97.0,NaN,37.0,24.5,11.0,2475.0,non-USA
40,Honda,Sporty,17.0,19.8,22.7,24.0,31.0,Driver & Passenger,Front,4,...,NaN,4.0,175.0,100.0,70.0,39.0,23.5,8.0,2865.0,non-USA
41,Honda,Small,8.4,12.1,15.8,42.0,46.0,Driver only,Front,4,...,11.9,4.0,173.0,NaN,67.0,36.0,28.0,12.0,NaN,non-USA
42,Honda,Compact,13.8,17.5,21.2,24.0,31.0,Driver & Passenger,Front,4,...,17.0,4.0,185.0,107.0,67.0,41.0,28.0,14.0,3040.0,non-USA
43,Hyundai,Small,6.8,8.0,9.2,29.0,33.0,None,Front,4,...,11.9,5.0,168.0,94.0,63.0,35.0,26.0,11.0,2345.0,non-USA
44,Hyundai,Small,9.0,10.0,11.0,NaN,29.0,None,Front,4,...,13.7,5.0,172.0,98.0,66.0,36.0,28.0,12.0,2620.0,non-USA
45,Hyundai,NaN,9.1,10.0,11.0,26.0,34.0,None,Front,4,...,11.9,4.0,166.0,94.0,64.0,34.0,23.5,9.0,2285.0,non-USA
46,Hyundai,Midsize,12.4,13.9,15.3,20.0,27.0,None,Front,4,...,17.2,5.0,184.0,104.0,69.0,41.0,31.0,NaN,2885.0,NaN
47,Infiniti,Midsize,45.4,47.9,NaN,17.0,22.0,NaN,Rear,8,...,22.5,5.0,200.0,113.0,72.0,42.0,29.0,15.0,4000.0,non-USA
48,Lexus,Midsize,27.5,28.0,28.4,18.0,24.0,Driver only,Front,6,...,18.5,5.0,188.0,103.0,70.0,40.0,27.5,14.0,3510.0,non-USA
49,NaN,Midsize,34.7,35.2,35.6,18.0,23.0,Driver & Passenger,Rear,6,...,NaN,4.0,191.0,106.0,71.0,39.0,25.0,9.0,3515.0,non-USA
50,Lincoln,Midsize,33.3,34.3,35.3,17.0,26.0,Driver & Passenger,NaN,6,...,18.4,6.0,205.0,109.0,73.0,42.0,30.0,19.0,3695.0,USA
51,Lincoln,Large,34.4,36.1,37.8,18.0,26.0,Driver & Passenger,Rear,8,...,20.0,NaN,219.0,117.0,77.0,45.0,31.5,22.0,4055.0,USA
52,Mazda,Small,7.4,8.3,9.1,29.0,37.0,None,Front,4,...,13.2,4.0,164.0,97.0,66.0,34.0,27.0,16.0,2325.0,non-USA
53,Mazda,Small,10.9,11.6,12.3,28.0,36.0,None,Front,4,...,14.5,5.0,172.0,98.0,66.0,36.0,26.5,13.0,2440.0,non-USA
54,Mazda,Compact,14.3,16.5,18.7,26.0,34.0,Driver only,Front,4,...,15.5,5.0,184.0,103.0,69.0,40.0,29.5,14.0,2970.0,non-USA
55,Mazda,Van,16.6,19.1,21.7,18.0,24.0,None,4WD,6,...,19.6,7.0,190.0,110.0,72.0,39.0,27.5,NaN,3735.0,non-USA
56,Mazda,Sporty,32.5,32.5,32.5,17.0,25.0,Driver only,NaN,rotary,...,20.0,2.0,169.0,96.0,69.0,NaN,NaN,NaN,NaN,non-USA
57,Mercedes-Benz,Compact,29.0,31.9,34.9,NaN,29.0,Driver only,Rear,4,...,14.5,5.0,175.0,105.0,67.0,34.0,26.0,12.0,2920.0,NaN
58,Mercedes-Benz,Midsize,43.8,61.9,80.0,19.0,25.0,Driver & Passenger,Rear,6,...,18.5,5.0,NaN,110.0,69.0,37.0,NaN,15.0,3525.0,non-USA
59,Mercury,Sporty,13.3,14.1,15.0,23.0,26.0,Driver only,Front,4,...,11.1,4.0,166.0,95.0,65.0,36.0,19.0,6.0,2450.0,USA
60,Mercury,Midsize,14.9,14.9,14.9,19.0,26.0,None,Rear,6,...,18.0,5.0,199.0,113.0,73.0,38.0,28.0,15.0,3610.0,USA
61,Mitsubishi,Small,7.7,10.3,12.9,29.0,NaN,None,Front,4,...,13.2,5.0,172.0,98.0,67.0,36.0,26.0,11.0,2295.0,non-USA
62,Mitsubishi,Midsize,22.4,26.1,NaN,18.0,24.0,Driver only,Front,6,...,19.0,5.0,190.0,107.0,70.0,43.0,27.5,14.0,3730.0,non-USA
63,Nissan,Small,8.7,11.8,14.9,29.0,33.0,Driver only,Front,NaN,...,13.2,5.0,170.0,96.0,66.0,33.0,26.0,NaN,NaN,non-USA
64,Nissan,Compact,13.0,15.7,18.3,24.0,30.0,Driver only,Front,4,...,15.9,5.0,181.0,103.0,67.0,40.0,28.5,14.0,3050.0,non-USA
65,Nissan,Van,16.7,19.1,21.5,17.0,23.0,None,Front,6,...,20.0,7.0,190.0,112.0,74.0,41.0,27.0,NaN,4100.0,non-USA
66,Nissan,Midsize,21.0,21.5,22.0,21.0,26.0,Driver only,Front,6,...,18.5,5.0,188.0,104.0,69.0,41.0,28.5,14.0,3200.0,non-USA
67,Oldsmobile,Compact,13.0,13.5,14.0,24.0,31.0,None,Front,4,...,15.2,5.0,188.0,103.0,67.0,39.0,28.0,14.0,2910.0,USA
68,Oldsmobile,Midsize,14.2,16.3,18.4,23.0,31.0,Driver only,Front,4,...,NaN,5.0,190.0,105.0,70.0,42.0,28.0,16.0,2890.0,USA
69,Oldsmobile,Van,19.5,19.5,19.5,18.0,23.0,None,Front,6,...,20.0,7.0,NaN,110.0,74.0,44.0,30.5,NaN,3715.0,USA
70,Oldsmobile,Large,19.5,20.7,21.9,NaN,28.0,Driver only,Front,6,...,18.0,6.0,201.0,111.0,74.0,42.0,31.5,17.0,3470.0,USA
71,Plymouth,Sporty,11.4,14.4,17.4,NaN,30.0,None,4WD,4,...,15.9,4.0,173.0,97.0,67.0,39.0,24.5,8.0,2640.0,NaN
72,Pontiac,Small,NaN,9.0,9.9,31.0,41.0,None,Front,4,...,13.2,4.0,177.0,99.0,66.0,35.0,25.5,17.0,2350.0,USA
73,Pontiac,Compact,9.4,11.1,12.8,NaN,31.0,None,NaN,4,...,15.2,5.0,181.0,101.0,66.0,39.0,25.0,13.0,NaN,USA
74,Pontiac,NaN,14.0,17.7,21.4,19.0,28.0,Driver & Passenger,Rear,6,...,15.5,4.0,196.0,101.0,75.0,43.0,25.0,13.0,3240.0,USA
75,Pontiac,Midsize,15.4,18.5,21.6,19.0,27.0,None,Front,6,...,16.5,5.0,195.0,108.0,72.0,41.0,28.5,16.0,3450.0,USA
76,Pontiac,Large,19.4,24.4,29.4,19.0,28.0,Driver & Passenger,Front,6,...,18.0,6.0,177.0,111.0,74.0,43.0,30.5,18.0,3495.0,USA
77,Saab,Compact,20.3,28.7,37.1,20.0,26.0,NaN,Front,4,...,18.0,5.0,NaN,99.0,67.0,37.0,26.5,14.0,2775.0,non-USA
78,Saturn,Small,9.2,NaN,12.9,NaN,38.0,Driver only,Front,4,...,12.8,5.0,176.0,102.0,68.0,40.0,26.5,NaN,2495.0,USA
79,Subaru,Small,7.3,8.4,9.5,33.0,37.0,None,4WD,3,...,9.2,4.0,146.0,90.0,60.0,32.0,23.5,10.0,2045.0,non-USA
80,Subaru,Small,10.5,10.9,11.3,25.0,30.0,None,4WD,4,...,15.9,5.0,175.0,97.0,65.0,35.0,27.5,15.0,2490.0,non-USA
81,Subaru,Compact,16.3,19.5,22.7,23.0,30.0,Driver only,4WD,4,...,15.9,5.0,179.0,102.0,67.0,37.0,27.0,14.0,3085.0,non-USA
82,Suzuki,NaN,7.3,8.6,NaN,39.0,43.0,None,Front,3,...,10.6,4.0,161.0,93.0,NaN,34.0,27.5,10.0,1965.0,non-USA
83,Toyota,Small,NaN,9.8,11.8,32.0,37.0,Driver only,Front,4,...,11.9,NaN,162.0,94.0,NaN,36.0,24.0,11.0,2055.0,non-USA
84,Toyota,Sporty,14.2,18.4,22.6,25.0,32.0,NaN,Front,4,...,15.9,4.0,174.0,99.0,69.0,NaN,23.0,13.0,2950.0,non-USA
85,Toyota,Midsize,15.2,NaN,21.2,22.0,29.0,Driver only,NaN,4,...,18.5,5.0,188.0,103.0,70.0,38.0,28.5,15.0,3030.0,non-USA
86,Toyota,Van,NaN,22.7,26.6,18.0,22.0,Driver only,4WD,4,...,19.8,7.0,187.0,113.0,71.0,41.0,35.0,NaN,3785.0,non-USA
87,Volkswagen,Small,8.7,9.1,9.5,25.0,33.0,None,Front,4,...,12.4,4.0,163.0,93.0,63.0,34.0,26.0,10.0,2240.0,non-USA
88,Volkswagen,Van,16.6,19.7,22.7,17.0,21.0,None,Front,5,...,21.1,7.0,187.0,115.0,72.0,38.0,34.0,NaN,3960.0,NaN
89,Volkswagen,Compact,17.6,20.0,22.4,21.0,30.0,None,Front,4,...,18.5,5.0,180.0,103.0,67.0,35.0,31.5,14.0,2985.0,non-USA
90,Volkswagen,Sporty,22.9,23.3,23.7,18.0,25.0,None,Front,6,...,18.5,4.0,159.0,97.0,66.0,36.0,26.0,15.0,2810.0,non-USA
91,Volvo,Compact,21.8,22.7,23.5,21.0,28.0,Driver only,Rear,NaN,...,15.8,5.0,190.0,104.0,67.0,37.0,29.5,14.0,2985.0,non-USA
92,NaN,Midsize,24.8,26.7,28.5,20.0,28.0,Driver & Passenger,Front,5,...,19.3,5.0,184.0,105.0,69.0,38.0,30.0,15.0,3245.0,non-USA

In [625]:
for i in numeric_columns:
    if df[i].count() == df[i].nunique():
        df = df.drop([i], axis = 1)
#df

In [626]:
#5 –î–ª—è —Å—Ç–æ–ª–±—Ü–æ–≤ —É –∫–æ—Ç–æ—Ä—ã—Ö –∑–Ω–∞—á–µ–Ω–∏–π –±–æ–ª–µ–µ 10, –æ—Å—Ç–∞–≤–ª—è–µ–º —Ç–æ–ø 10 –∑–Ω–∞—á–µ–Ω–∏–π, –æ—Å—Ç–∞–ª—å–Ω—ã–µ –∑–∞–º–µ–Ω—è–µ–º –Ω–∞ 'other'
for i in df.columns:
    val = df[i].nunique()
    if val > 10:
        if df[i].count() > 10:
            df = df.replace(df[i].value_counts().index[10:], 'other')
        else:
            continue
    else:
        continue
pd.set_option('max_rows',100)
print(df)

   Manufacturer     Type Min_Price  Price Max_Price MPG_city MPG_highway  \
0         other    Small     other   15.9     other       25          31
1           NaN  Midsize     other  other     other    other          25
2         other  Compact     other  other     other    other          26
3         other  Midsize       NaN  other     other    other          26
4         other  Midsize       NaN  other       NaN    other       other
5         Buick  Midsize     other   15.7     other    other          31
6         Buick    Large     other  other       NaN    other       other
7         Buick    Large     other  other      24.9       16          25
8         Buick  Midsize     other  other     other    other          27
9         other    Large     other  other     other       16          25
10        other  Midsize     other  other     other       16          25
11    Chevrolet  Compact     other  other      18.3       25       other
12    Chevrolet  Compact     other  other     other       25       other
13    Chevrolet   Sporty     other  other     other    other       other
14    Chevrolet  Midsize     other   15.9     other      NaN       other
15    Chevrolet      Van     other  other     other    other          23
16    Chevrolet      Van     other  other     other    other       other
17    Chevrolet    Large     other  other     other    other          26
18    Chevrolet   Sporty     other  other     other    other          25
19          NaN    Large     other  other     other    other       other
20        other  Compact     other  other     other       23       other
21        other    Large     other  other     other    other          26
22        Dodge    Small     other  other     other    other       other
23        Dodge    Small       8.4  other     other       23       other
24        Dodge  Compact     other  other     other    other          27
25        Dodge      Van       NaN  other     other    other       other
26        Dodge  Midsize     other  other     other    other         NaN
27        Dodge   Sporty     other  other     other      NaN          24
28        other    Small     other  other     other    other       other
29        other    Large       NaN  other      21.2    other       other
30         Ford    Small     other  other     other       31       other
31         Ford    Small       8.4  other     other       23       other
32         Ford  Compact     other  other     other    other          27
33         Ford   Sporty     other   15.9     other    other       other
34         Ford   Sporty     other  other     other      NaN       other
35         Ford      Van     other  other     other    other       other
36         Ford  Midsize     other  other     other    other       other
37         Ford    Large     other  other      21.7    other          26
38        other    Small     other    8.4     other    other       other
39        other   Sporty     other  other     other    other       other
40        other   Sporty     other  other      22.7       24          31
41        other    Small       8.4  other     other       42       other
42        other  Compact     other  other      21.2       24          31
43      Hyundai    Small     other  other     other    other       other
44      Hyundai    Small     other  other        11      NaN       other
45      Hyundai      NaN     other  other        11       26       other
46      Hyundai  Midsize     other  other      15.3    other          27
47        other  Midsize     other  other       NaN    other       other
48        other  Midsize     other  other     other    other          24
49          NaN  Midsize     other  other     other    other          23
50        other  Midsize     other  other     other    other          26
51        other    Large     other  other     other    other          26
52        Mazda    Small     other  other     other    other          37
53        Mazda    Small     other  other     other    other       other
54        Mazda  Compact     other  other     other       26       other
55        Mazda      Van     other   19.1      21.7    other          24
56        Mazda   Sporty     other  other     other    other          25
57        other  Compact     other  other     other      NaN       other
58        other  Midsize     other  other     other    other          25
59        other   Sporty     other  other     other       23          26
60        other  Midsize     other  other     other    other          26
61        other    Small     other  other     other    other         NaN
62        other  Midsize     other  other       NaN    other          24
63       Nissan    Small       8.7  other     other    other       other
64       Nissan  Compact        13   15.7      18.3       24       other
65       Nissan      Van     other   19.1     other    other          23
66       Nissan  Midsize     other  other     other    other          26
67   Oldsmobile  Compact        13  other     other       24          31
68   Oldsmobile  Midsize     other  other     other       23          31
69   Oldsmobile      Van     other  other     other    other          23
70   Oldsmobile    Large     other  other     other      NaN       other
71        other   Sporty     other  other     other      NaN       other
72      Pontiac    Small       NaN  other     other       31       other
73      Pontiac  Compact     other  other     other      NaN          31
74      Pontiac      NaN     other  other     other    other       other
75      Pontiac  Midsize     other  other      21.6    other          27
76      Pontiac    Large     other  other     other    other       other
77        other  Compact     other  other     other    other          26
78        other    Small     other    NaN     other      NaN       other
79        other    Small       7.3    8.4       9.5    other          37
80        other    Small     other  other     other       25       other
81        other  Compact     other  other      22.7       23       other
82        other      NaN       7.3  other       NaN    other       other
83       Toyota    Small       NaN  other     other    other          37
84       Toyota   Sporty     other  other     other       25       other
85       Toyota  Midsize     other    NaN      21.2    other       other
86       Toyota      Van       NaN   22.7     other    other       other
87        other    Small       8.7  other       9.5       25       other
88        other      Van     other   19.7      22.7    other       other
89        other  Compact     other  other     other    other       other
90        other   Sporty     other  other     other    other          25
91        other  Compact     other   22.7     other    other       other
92          NaN  Midsize     other  other     other    other       other

               AirBags DriveTrain Cylinders  ... Fuel_tank_capacity  \
0                 None      Front         4  ...               13.2
1   Driver & Passenger      Front         6  ...              other
2          Driver only      Front         6  ...              other
3   Driver & Passenger        NaN         6  ...               21.1
4                  NaN       Rear         4  ...               21.1
5          Driver only        NaN         4  ...              other
6          Driver only      Front         6  ...                NaN
7          Driver only       Rear         6  ...                 23
8          Driver only      Front         6  ...              other
9          Driver only      Front         8  ...              other
10  Driver & Passenger      Front         8  ...              other
11                 NaN        NaN         4  ...              other
12         Driver only      Front       NaN  ...              other
13  Driver & Passenger       Rear       NaN  ...                NaN
14                None      Front         4  ...              other
15                None      Front         6  ...              other
16                None        4WD         6  ...                 27
17         Driver only       Rear         8  ...                 23
18         Driver only       Rear         8  ...              other
19  Driver & Passenger      Front         6  ...              other
20  Driver & Passenger      Front         4  ...                 16
21         Driver only      Front         6  ...                 16
22                None      Front         4  ...                NaN
23         Driver only      Front         4  ...              other
24         Driver only      Front         4  ...                NaN
25         Driver only        4WD         6  ...              other
26         Driver only      Front       NaN  ...                 16
27         Driver only        4WD         6  ...              other
28                None      Front         4  ...               13.2
29  Driver & Passenger      Front         6  ...              other
30                 NaN      Front         4  ...              other
31                None      Front         4  ...               13.2
32                None      Front         4  ...               15.9
33         Driver only       Rear         4  ...              other
34         Driver only      Front         4  ...               15.5
35         Driver only        4WD         6  ...              other
36         Driver only      Front         6  ...                NaN
37         Driver only       Rear         8  ...              other
38                None      Front         3  ...              other
39         Driver only      Front         4  ...              other
40  Driver & Passenger      Front         4  ...                NaN
41         Driver only      Front         4  ...              other
42  Driver & Passenger      Front         4  ...              other
43                None      Front         4  ...              other
44                None      Front         4  ...               13.7
45                None      Front         4  ...              other
46                None      Front         4  ...              other
47                 NaN       Rear         8  ...               22.5
48         Driver only      Front         6  ...              other
49  Driver & Passenger       Rear         6  ...                NaN
50  Driver & Passenger        NaN         6  ...              other
51  Driver & Passenger       Rear         8  ...              other
52                None      Front         4  ...               13.2
53                None      Front         4  ...              other
54         Driver only      Front         4  ...               15.5
55                None        4WD         6  ...              other
56         Driver only        NaN    rotary  ...              other
57         Driver only       Rear         4  ...              other
58  Driver & Passenger       Rear         6  ...              other
59         Driver only      Front         4  ...              other
60                None       Rear         6  ...              other
61                None      Front         4  ...               13.2
62         Driver only      Front         6  ...              other
63         Driver only      Front       NaN  ...               13.2
64         Driver only      Front         4  ...               15.9
65                None      Front         6  ...              other
66         Driver only      Front         6  ...              other
67                None      Front         4  ...              other
68         Driver only      Front         4  ...                NaN
69                None      Front         6  ...              other
70         Driver only      Front         6  ...              other
71                None        4WD         4  ...               15.9
72                None      Front         4  ...               13.2
73                None        NaN         4  ...              other
74  Driver & Passenger       Rear         6  ...               15.5
75                None      Front         6  ...              other
76  Driver & Passenger      Front         6  ...              other
77                 NaN      Front         4  ...              other
78         Driver only      Front         4  ...              other
79                None        4WD         3  ...              other
80                None        4WD         4  ...               15.9
81         Driver only        4WD         4  ...               15.9
82                None      Front         3  ...              other
83         Driver only      Front         4  ...              other
84                 NaN      Front         4  ...               15.9
85         Driver only        NaN         4  ...              other
86         Driver only        4WD         4  ...              other
87                None      Front         4  ...              other
88                None      Front         5  ...               21.1
89                None      Front         4  ...              other
90                None      Front         6  ...              other
91         Driver only       Rear       NaN  ...              other
92  Driver & Passenger      Front         5  ...              other

   Passengers Length Wheelbase  Width Turn_circle Rear_seat_room Luggage_room  \
0       other    177       102     68          37           26.5          NaN
1       other  other     other     71       other          other        other
2       other  other       102     67          37          other        other
3           6  other       106    NaN          37             31        other
4           4  other     other     69       other             27           13
5           6  other     other     69       other          other           16
6           6  other       111  other          42           30.5        other
7           6  other     other     78          45           30.5        other
8       other  other     other    NaN       other           26.5        other
9           6  other     other  other       other          other        other
10      other  other       111  other          44             31          NaN
11      other  other       101     66       other             25           13
12      other    184     other     68       other             26          NaN
13          4  other       101  other       other             25           13
14          6    NaN     other     71         NaN          other           16
15          7  other       110  other          44           30.5          NaN
16      other  other       111     78          42          other          NaN
17          6  other     other     77          42          other        other
18          2    179     other  other       other            NaN          NaN
19          6  other       113  other         NaN             31        other
20          6  other       104     68       other           30.5        other
21          6  other       110     69          44          other        other
22      other    174        98     66       other            NaN           11
23      other    172        97     67       other           26.5          NaN
24          6    181       104     68       other           30.5          NaN
25          7    175     other     72          42           26.5          NaN
26          6    192     other     69          42           30.5           16
27          4  other        97    NaN          40          other           11
28      other    174        98     66       other           26.5           11
29          6  other       113  other          40          other        other
30          4  other     other  other       other             26           12
31      other  other        98     67       other          other           12
32      other    177     other     68         NaN          other           13
33          4  other       101     68          40             24           12
34          4    179     other  other       other             23        other
35          7  other     other     72          45          other          NaN
36      other    192       106     71          40          other        other
37          6  other     other     78       other          other        other
38          4  other     other  other       other          other        other
39          4  other        97    NaN          37          other           11
40          4    175     other  other       other          other        other
41          4  other       NaN     67       other          other           12
42          4  other     other     67       other          other        other
43      other  other     other  other       other             26           11
44      other    172        98     66       other          other           12
45          4  other     other  other       other          other        other
46      other    184       104     69       other             31          NaN
47      other  other       113     72          42          other        other
48      other    188     other  other          40          other        other
49          4  other       106     71       other             25        other
50          6  other     other  other          42          other        other
51        NaN  other     other     77          45           31.5        other
52          4  other        97     66       other             27           16
53      other    172        98     66       other           26.5           13
54      other    184     other     69          40          other        other
55          7  other       110     72       other          other          NaN
56          2  other     other     69         NaN            NaN          NaN
57      other    175     other     67       other             26           12
58      other    NaN       110     69          37            NaN        other
59          4  other     other     65       other          other            6
60      other  other       113  other       other          other        other
61      other    172        98     67       other             26           11
62      other  other     other  other       other          other        other
63      other  other     other     66       other             26          NaN
64      other    181     other     67          40          other        other
65          7  other     other  other       other             27          NaN
66      other    188       104     69       other          other        other
67      other    188     other     67       other          other        other
68      other  other     other  other          42          other           16
69          7    NaN       110  other          44           30.5          NaN
70          6  other       111  other          42           31.5        other
71          4  other        97     67       other          other        other
72          4    177     other     66       other          other        other
73      other    181       101     66       other             25           13
74          4  other       101  other       other             25           13
75      other  other     other     72       other          other           16
76          6    177       111  other       other           30.5        other
77      other    NaN     other     67          37           26.5        other
78      other  other       102     68          40           26.5          NaN
79          4  other     other  other       other          other        other
80      other    175        97     65       other          other        other
81      other    179       102     67          37             27        other
82          4  other     other    NaN       other          other        other
83        NaN  other     other    NaN       other             24           11
84          4    174     other     69         NaN             23           13

In [627]:
#6 –ß–∏—Å–ª–æ–≤—ã–µ —Å—Ç–æ–ª–±—Ü—ã –ø—Ä–æ–≤–µ—Ä—è–µ–º –Ω–∞ –ø—Ä–æ–ø—É—Å–∫–∏. –ü–æ–¥—Å—á–∏—Ç—ã–≤–∞–µ–º –∫–æ–ª-–≤–æ nan\none –∏ –¥–µ–ª–∏–º –Ω–∞ —Ä–∞–∑–º–µ—Ä –¥–∞—Ç–∞—Ñ—Ä–µ–π–º–∞ 
#-—Å–æ—Ö—Ä–∞–Ω—è–µ–º –≤ –æ—Ç–¥–µ–ª—å–Ω—ã–π –¥–∞—Ç–∞—Ñ—Ä–µ–π–º, —ç—Ç–æ –¥–æ–ª—è –ø—Ä–æ–ø—É—Å–∫–æ–≤ –≤ –∫–∞–∂–¥–æ–º —Å—Ç–æ–ª–±—Ü–µ

(df[numeric_columns.columns].isnull().sum()/df[numeric_columns.columns].size).to_frame()

                           0
Min_Price           0.004182
Price               0.001195
Max_Price           0.002987
MPG_city            0.005376
MPG_highway         0.001195
EngineSize          0.001195
Horsepower          0.004182
RPM                 0.001792
Rev_per_mile        0.003584
Fuel_tank_capacity  0.004779
Passengers          0.001195
Length              0.002389
Wheelbase           0.000597
Width               0.003584
Turn_circle         0.002987
Rear_seat_room      0.002389
Luggage_room        0.011350
Weight              0.004182

In [639]:
df[numeric_columns.columns].values

array([['other', 15.9, 'other', ..., 26.5, nan, 'other'],
       ['other', 'other', 'other', ..., 'other', 'other', 'other'],
       ['other', 'other', 'other', ..., 'other', 'other', 'other'],
       ...,
       ['other', 'other', 'other', ..., 26.0, 'other', 'other'],
       ['other', 22.7, 'other', ..., 'other', 'other', 2985.0],
       ['other', 'other', 'other', ..., 'other', 'other', 'other']],
      dtype=object)

In [643]:
#7 –ß–∏—Å—Ç–∏–º –≤—ã–±—Ä–æ—Å—ã. –í–æ –≤—Å–µ—Ö —á–∏—Å–ª–æ–≤—ã—Ö —Å—Ç–æ–ª–±—Ü–∞—Ö –∑–∞–º–µ–Ω—è–µ–º –≤—Å–µ –∑–Ω–∞—á–µ–Ω–∏—è —Å—Ç–æ–ª–±—Ü–∞ –º–µ–Ω—å—à–µ 5–≥–æ –ø–µ—Ä—Å–µ–Ω—Ç–∏–ª—è –∏ –±–æ–ª—å—à–µ 95–æ–≥–æ –ø–µ—Ä—Å–µ–Ω—Ç–∏–ª—è 
#–Ω–∞ —ç—Ç–∏ –ø–æ–≥—Ä–∞–Ω–∏—á–Ω—ã–µ –∑–Ω–∞—á–µ–Ω–∏—è.
q1 = df[numeric_columns.columns].quantile(.05, axis = 1)
q2 = df[numeric_columns.columns].quantile(.95, axis = 1)
print(q1)
print()
print(q2)

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
5    NaN
6    NaN
7    NaN
8    NaN
9    NaN
10   NaN
11   NaN
12   NaN
13   NaN
14   NaN
15   NaN
16   NaN
17   NaN
18   NaN
19   NaN
20   NaN
21   NaN
22   NaN
23   NaN
24   NaN
25   NaN
26   NaN
27   NaN
28   NaN
29   NaN
30   NaN
31   NaN
32   NaN
33   NaN
34   NaN
35   NaN
36   NaN
37   NaN
38   NaN
39   NaN
40   NaN
41   NaN
42   NaN
43   NaN
44   NaN
45   NaN
46   NaN
47   NaN
48   NaN
49   NaN
50   NaN
51   NaN
52   NaN
53   NaN
54   NaN
55   NaN
56   NaN
57   NaN
58   NaN
59   NaN
60   NaN
61   NaN
62   NaN
63   NaN
64   NaN
65   NaN
66   NaN
67   NaN
68   NaN
69   NaN
70   NaN
71   NaN
72   NaN
73   NaN
74   NaN
75   NaN
76   NaN
77   NaN
78   NaN
79   NaN
80   NaN
81   NaN
82   NaN
83   NaN
84   NaN
85   NaN
86   NaN
87   NaN
88   NaN
89   NaN
90   NaN
91   NaN
92   NaN
Name: 0.05, dtype: float64

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
5    NaN
6    NaN
7    NaN
8    NaN
9    NaN
10   NaN
11   NaN
12   NaN
13   NaN
14   NaN
15   NaN
16   NaN
17   NaN
18   NaN
19   NaN
20   NaN
21   NaN
22   NaN
23   NaN
24   NaN
25   NaN
26   NaN
27   NaN
28   NaN
29   NaN
30   NaN
31   NaN
32   NaN
33   NaN
34   NaN
35   NaN
36   NaN
37   NaN
38   NaN
39   NaN
40   NaN
41   NaN
42   NaN
43   NaN
44   NaN
45   NaN
46   NaN
47   NaN
48   NaN
49   NaN
50   NaN
51   NaN
52   NaN
53   NaN
54   NaN
55   NaN
56   NaN
57   NaN
58   NaN
59   NaN
60   NaN
61   NaN
62   NaN
63   NaN
64   NaN
65   NaN
66   NaN
67   NaN
68   NaN
69   NaN
70   NaN
71   NaN
72   NaN
73   NaN
74   NaN
75   NaN
76   NaN
77   NaN
78   NaN
79   NaN
80   NaN
81   NaN
82   NaN
83   NaN
84   NaN
85   NaN
86   NaN
87   NaN
88   NaN
89   NaN
90   NaN
91   NaN
92   NaN
Name: 0.95, dtype: float64

In [ ]:
df[df < q1] = q1
df

In [433]:
#8 –ó–∞–ø–æ–ª–Ω—è–µ–º –ø—Ä–æ–ø—É—Å–∫–∏ –≤ —á–∏—Å–ª–æ–≤—ã—Ö —Å—Ç–æ–ª–±—Ü–∞—Ö –Ω–∞ —Å—Ä–µ–¥–Ω–µ–µ –ø–æ —Å—Ç–æ–ª–±—Ü—É, –≤ —Ç–µ–∫—Å—Ç–æ–≤—ã—Ö —Å—Ç–æ–ª–±—Ü–∞—Ö –Ω–∞ 'other'
df[numeric_columns.columns].fillna(df[numeric_columns.columns].mean())

,Min_Price,Price,Max_Price,MPG_city,MPG_highway,EngineSize,Horsepower,RPM,Rev_per_mile,Fuel_tank_capacity,Passengers,Length,Wheelbase,Width,Turn_circle,Rear_seat_room,Luggage_room,Weight
0,other,15.9,other,25,31,1.8,140,other,other,13.2,other,177,102,68,37,26.5,NaN,other
1,other,other,other,other,25,other,other,5500,2335,other,other,other,other,71,other,other,other,other
2,other,other,other,other,26,other,172,5500,other,other,other,other,102,67,37,other,other,other
3,NaN,other,other,other,26,NaN,172,5500,2535,21.1,6,other,106,NaN,37,31,other,other
4,NaN,other,NaN,other,other,other,other,other,other,21.1,4,other,other,69,other,27,13,other
5,other,15.7,other,other,31,2.2,110,5200,2565,other,6,other,other,69,other,other,16,NaN
6,other,other,NaN,other,other,3.8,other,4800,NaN,NaN,6,other,111,other,42,30.5,other,3470
7,other,other,24.9,16,25,other,other,other,other,23,6,other,other,78,45,30.5,other,other
8,other,other,other,other,27,3.8,other,4800,1690,other,other,other,other,NaN,other,26.5,other,3495
9,other,other,other,16,25,other,other,other,NaN,other,6,other,other,other,other,other,other,other
10,other,other,other,16,25,other,other,6000,other,other,other,other,111,other,44,31,NaN,other
11,other,other,18.3,25,other,2.2,NaN,5200,2380,other,other,other,101,66,other,25,13,2490
12,other,other,other,25,other,2.2,110,5200,2665,other,other,184,other,68,other,26,NaN,other
13,other,other,other,other,other,other,160,4600,1805,NaN,4,other,101,other,other,25,13,3240
14,other,15.9,other,NaN,other,2.2,NaN,5200,other,other,6,NaN,other,71,NaN,other,16,other
15,other,other,other,other,23,3.8,other,4800,1690,other,7,other,110,other,44,30.5,NaN,other
16,other,other,other,other,other,other,NaN,other,other,27,other,other,111,78,42,other,NaN,other
17,other,other,other,other,26,other,other,other,other,23,6,other,other,77,42,other,other,other
18,other,other,other,other,25,other,300,5000,other,other,2,179,other,other,other,NaN,NaN,other
19,other,other,other,other,other,other,other,other,other,other,6,other,113,other,NaN,31,other,other
20,other,other,other,23,other,3,other,5000,other,16,6,other,104,68,other,30.5,other,3085
21,other,other,other,other,26,other,other,4800,other,16,6,other,110,69,44,other,other,other
22,other,other,other,other,other,1.5,92,6000,other,NaN,other,174,98,66,other,NaN,11,other
23,8.4,other,other,23,other,2.2,other,4800,NaN,other,other,172,97,67,other,26.5,NaN,other
24,other,other,other,other,27,2.5,other,4800,2535,NaN,6,181,104,68,other,30.5,NaN,2970
25,NaN,other,other,other,other,3,other,5000,other,other,7,175,other,72,42,26.5,NaN,other
26,other,other,other,other,NaN,2.5,other,4800,other,16,6,192,other,69,42,30.5,16,other
27,other,other,other,NaN,24,3,300,6000,other,other,4,other,97,NaN,40,other,11,other
28,other,other,other,other,other,1.5,92,6000,2505,13.2,other,174,98,66,other,26.5,11,2295
29,NaN,other,21.2,other,other,other,NaN,5800,other,other,6,other,113,other,40,other,other,other
30,other,other,other,31,other,other,other,5000,other,other,4,other,other,other,other,26,12,other
31,8.4,other,other,23,other,1.8,other,other,other,13.2,other,other,98,67,other,other,12,other
32,other,other,other,other,27,2.3,other,other,other,15.9,other,177,other,68,NaN,other,13,NaN
33,other,15.9,other,other,other,2.3,other,4600,other,other,4,other,101,68,40,24,12,NaN
34,other,other,other,NaN,other,2,other,5500,2340,15.5,4,179,other,other,other,23,other,other
35,other,other,other,other,other,3,other,4800,other,other,7,other,other,72,45,other,NaN,3735
36,other,other,other,other,other,3,NaN,4800,other,NaN,other,192,106,71,40,other,other,other
37,other,other,21.7,other,26,other,other,other,NaN,other,6,other,other,78,other,other,other,other
38,other,8.4,other,other,other,other,other,other,other,other,4,other,other,other,other,other,other,other
39,other,other,other,other,other,1.6,other,5400,other,other,4,other,97,NaN,37,other,11,other
40,other,other,22.7,24,31,2.3,160,5800,other,NaN,4,175,other,other,other,other,other,other
41,8.4,other,other,42,other,1.5,NaN,other,other,other,4,other,NaN,67,other,other,12,NaN
42,other,other,21.2,24,31,2.2,140,5600,NaN,other,4,other,other,67,other,other,other,other
43,other,other,other,other,other,1.5,other,5500,other,other,other,other,other,other,other,26,11,other
44,other,other,11,NaN,other,1.8,other,6000,other,13.7,other,172,98,66,other,other,12,other
45,other,other,11,26,other,1.5,92,other,other,other,4,other,other,other,other,other,other,other
46,other,other,15.3,other,27,2,other,6000,2335,other,other,184,104,69,other,31,NaN,other
47,other,other,NaN,other,other,other,other,6000,other,22.5,other,other,113,72,42,other,other,other
48,other,other,other,other,24,3,other,NaN,other,other,other,188,other,other,40,other,other,other
49,other,other,other,other,23,3,other,6000,other,NaN,4,other,106,71,other,25,other,other
50,other,other,other,other,26,3.8,160,other,other,other,6,other,other,other,42,other,other,other
51,other,other,other,other,26,other,other,4600,other,other,NaN,other,other,77,45,31.5,other,other
52,other,other,other,other,37,1.6,other,5000,other,13.2,4,other,97,66,other,27,16,other
53,other,other,other,other,other,1.8,other,5500,other,other,other,172,98,66,other,26.5,13,other
54,other,other,other,26,other,2.5,other,5600,2505,15.5,other,184,other,69,40,other,other,2970
55,other,19.1,21.7,other,24,3,other,5000,other,other,7,other,110,72,other,other,NaN,3735
56,other,other,other,other,25,other,other,other,other,other,2,other,other,69,NaN,NaN,NaN,NaN
57,other,other,other,NaN,other,2.3,130,other,other,other,other,175,other,67,other,26,12,other
58,other,other,other,other,25,other,other,5500,other,other,other,NaN,110,69,37,NaN,other,other
59,other,other,other,23,26,1.6,other,other,other,other,4,other,other,65,other,other,6,other
60,other,other,other,other,26,3.8,140,other,other,other,other,other,113,other,other,other,other,other
61,other,other,other,other,NaN,1.5,92,6000,2505,13.2,other,172,98,67,other,26,11,2295
62,other,other,NaN,other,24,3,other,6000,other,other,other,other,other,other,other,other,other,other
63,8.7,other,other,other,other,1.6,110,6000,other,13.2,other,other,other,66,other,26,NaN,NaN
64,13,15.7,18.3,24,other,other,other,5600,other,15.9,other,181,other,67,40,other,other,other
65,other,19.1,other,other,23,3,NaN,4800,other,other,7,other,other,other,other,27,NaN,other
66,other,other,other,other,26,3,160,5200,other,other,other,188,104,69,other,other,other,other
67,13,other,other,24,31,2.3,other,6000,2380,other,other,188,other,67,other,other,other,other
68,other,other,other,23,31,2.2,110,5200,2565,NaN,other,other,other,other,42,other,16,other
69,other,other,other,other,23,3.8,other,4800,1690,other,7,NaN,110,other,44,30.5,NaN,other
70,other,other,other,NaN,other,3.8,other,4800,other,other,6,other,111,other,42,31.5,other,3470
71,other,other,other,NaN,other,1.8,92,5000,other,15.9,4,other,97,67,other,other,other,other
72,NaN,other,other,31,other,1.6,other,5600,other,13.2,4,177,other,66,other,other,other,other
73,other,other,other,NaN,31,2,110,5200,2665,other,other,181,101,66,other,25,13,NaN
74,other,other,other,other,other,NaN,160,4600,1805,15.5,4,other,101,other,other,25,13,3240
75,other,other,21.6,other,27,other,other,5000,other,other,other,other,other,72,other,other,16,other
76,other,other,other,other,other,3.8,other,4800,other,other,6,177,111,other,other,30.5,other,3495
77,other,other,other,other,26,other,140,6000,other,other,other,NaN,other,67,37,26.5,other,other
78,other,NaN,other,NaN,other,other,other,5000,other,other,other,other,102,68,40,26.5,NaN,other
79,7.3,8.4,9.5,other,37,other,other,5600,other,other,4,other,other,other,other,other,other,other
80,other,other,other,25,other,1.8,other,5200,other,15.9,other,175,97,65,other,other,other,2490
81,other,other,22.7,23,other,2.2,130,NaN,other,15.9,other,179,102,67,37,27,other,3085
82,7.3,other,NaN,other,other,other,other,6000,other,other,4,other,other,NaN,other,other,other,other
83,NaN,other,other,other,37,1.5,other,5200,other,other,NaN,other,other,NaN,other,24,11,other
84,other,other,other,25,other,2.2,other,NaN,other,15.9,4,174,other,69,NaN,23,13,other
85,other,NaN,21.2,other,other,2.2,130,5400,2340,other,other,188,other,other,other,other,other,other
86,NaN,22.7,other,other,other,other,other,5000,other,other,7,other,113,71,other,other,NaN,other
87,8.7,other,9.5,25,other,1.8,other,5500,other,other,4,other,other,other,other,26,other,other
88,other,19.7,22.7,other,other,2.5,other,other,other,21.1,7,other,other,72,other,other,NaN,other
89,other,other,other,other,other,2,other,5800,other,other,other,other,other,67,other,31.5,other,2985
90,other,other,other,other,25,other,other,5800,other,other,4,other,97,66,other,26,other,other
91,other,22.7,other,other,other,2.3,other,5400,other,other,other,other,104,67,37,other,other,2985
92,other,other,other,other,other,other,other,other,NaN,other,other,184,other,69,other,other,other,other

In [ ]:
#9 –í—Å–µ –∫–∞—Ç–µ–≥–æ—Ä–∏–∞–ª—å–Ω—ã–µ –ø—Ä–∏–∑–Ω–∞–∫–∏ –ø—Ä–µ–≤—Ä–∞—â–∞–µ–º –≤ one-hot-encoding

In [ ]:
#10 –°–æ–∑–¥–∞—Ç—å –Ω–æ–≤—ã–π —Å—Ç–æ–ª–±–µ—Ü Length_Width = Length * Width

In [ ]:
#11

In [ ]:
#12

In [ ]:
#13

In [ ]:
#14

In [ ]:
#15

In [ ]:
#16

# Regular expressions with Pandas

1. –í—ã–¥–µ–ª–∏—Ç—å –≤ –æ—Ç–¥–µ–ª—å–Ω—É—é –∫–æ–ª–æ–Ω–∫—É event_id –ø–µ—Ä–≤—É—é —Ü–∏—Ñ—Ä—É –≤ –∫–∞–≤—ã—á–∫–∞—Ö, –≤–æ –≤—Ç–æ—Ä—É—é –∫–æ–ª–æ–Ω–∫—É event_probability –≤–µ—Ä–æ—è—Ç–Ω–æ—Å—Ç—å (‚òÖ‚òÜ‚òÜ)

In [1152]:
df=pd.DataFrame({'col1':["{'34': 0.9839372122311848}",
                         "{'77': 0.6724645988404411}",
                         "{'77': 0.6491011266207006}",
                         "{'77': 0.6123085784265466}",
                         "{'34': 0.87}",
                         "{'77': 0.6225699652019304}",
                         "{'3': 0.5470808226524633}",
                         "{'77': 0.6233849004135044}",
                         "{'77': 0.7050888998743866}",
                         "{'52': 0.8945052223205372}"]})

#print(df)

new_df = df['col1'].str.split(r'\{\'|\':|}', expand=True)

new_df = new_df.drop(columns=[0,3])

new_df.columns=['event_id','event_probability']

print(new_df)

  event_id    event_probability
0       34   0.9839372122311848
1       77   0.6724645988404411
2       77   0.6491011266207006
3       77   0.6123085784265466
4       34                 0.87
5       77   0.6225699652019304
6        3   0.5470808226524633
7       77   0.6233849004135044
8       77   0.7050888998743866
9       52   0.8945052223205372

2. –£–¥–∞–ª–∏—Ç–µ –≤—Å–µ —Ç—ç–≥–∏, –ø–µ—Ä–µ–Ω–æ—Å—ã —Å—Ç—Ä–æ–∫ –∏–∑ —Ç–µ–∫—Å—Ç–æ–≤ –Ω–æ–≤–æ—Å—Ç–µ–π (‚òÖ‚òÖ‚òÖ)

(hint: df.column.str())

In [492]:
df = pd.read_excel('news.xlsx')
print(df)
print()
new_df = df['text'].str.replace(r'\<.*\w+.*>|\n|[ ]{2,}',  '')
new_df = new_df.to_frame()
print(new_df)

                                                 text
0   <html>\n <body>\n  <p>\n   –°–æ–æ–±—â–µ–Ω–∏–µ –æ —Å—É—â–µ—Å—Ç–≤...
1   <html>\n <body>\n  <p>\n   <mark-inn class="{5...
2   <html>\n <body>\n  <p>\n   <mark-sentence clas...
3   <html>\n <body>\n  <h3 id="header">\n   –°–∞–º–∞—Ä—Å...
4   <html>\n <body>\n  <p>\n   <mark-sentence clas...
5   <html>\n <body>\n  <p>\n   –í–æ –≤—Ä–µ–º—è —Ä–∞–±–æ—á–µ–π –ø–æ...
6   <html>\n <body>\n  <p>\n   –°–µ–≥–æ–¥–Ω—è –í–í–ü –†–æ—Å—Å–∏–∏ ...
7   <html>\n <body>\n  <p>\n   <span class="articl...
8   <html>\n <body>\n  <p>\n   –ú–ò–ù–ï–†–ê–õ–¨–ù–´–ï –í–û–î–´ /–°...
9   <html>\n <body>\n  <p>\n   <span>\n    04 –¥–µ–∫–∞...
10  <html>\n <body>\n  <p>\n   –ö–æ–Ω–∫—É—Ä—Å –Ω–∞ —Ä–µ–∫–æ–Ω—Å—Ç—Ä...
11  <html>\n <body>\n  <p>\n   –ù–∞–∑–≤–∞–Ω–∏–µ –∫–æ–º–ø–∞–Ω–∏–∏: ...
12  <html>\n <body>\n  <p>\n   –ú–û–°–ö–í–ê, 4 –¥–µ–∫ - –†–ò–ê...
13  <html>\n <body>\n  <p>\n   –ú–û–°–ö–í–ê, 4 –¥–µ–∫–∞–±—Ä—è./...
14  <html>\n <body>\n  <p>\n   –í —ç—Ç–æ–º –≥–æ–¥—É –≤ –ö–∞–ª—Ç–∞...
15  <html>\n <body>\n  <p>\n   <span class="articl...
16  <html>\n <body>\n  <p>\n   –¥–∞—Ç–∞: on –∏—Å—Ç–æ—á–Ω–∏–∫:\...
17  <html>\n <body>\n  <p>\n   <mark-inn>\n    –ù–£–†...
18  <html>\n <body>\n  <p>\n   <mark-inn>\n    Sam...
19  <html>\n <body>\n  <p>\n   –í –∞–¥–º–∏–Ω–∏—Å—Ç—Ä–∞—Ü–∏–∏ –ö—Ä–∞...

                                                 text
0    –°–æ–æ–±—â–µ–Ω–∏–µ –æ —Å—É—â–µ—Å—Ç–≤–µ–Ω–Ω–æ–º —Ñ–∞–∫—Ç–µ–æ –≤—ã–ø–ª–∞—á–µ–Ω–Ω—ã—Ö –¥...
1    –ù–ò–ñ–ù–ò–ô–ù–û–í–ì–û–†–û–î, 3 –¥–µ–∫–∞–±—Ä—è 2019, 22:41 - REGNU...
2    –£–õ–¨–Ø–ù–û–í–°–ö, 3 –¥–µ–∫–∞–±—Ä—è 2019, 11:38 - REGNUM –í–£–ª...
3    –°–∞–º–∞—Ä—Å–∫–∞—è –æ–±–ª–∞—Å—Ç—å –ø—Ä–∏–∑–Ω–∞–Ω–∞ –æ–¥–Ω–∏–º –∏–∑ –ª–∏–¥–µ—Ä–æ–≤ —Ä...
4    –û–∫—Ä—É–∂–Ω–∞—è –∞–¥–º–∏–Ω–∏—Å—Ç—Ä–∞—Ü–∏—è –Ø–∫—É—Ç—Å–∫–∞ –ø–æ–¥–ø–∏—Å–∞–ª–∞ —Å–æ–≥–ª...
5    –í–æ –≤—Ä–µ–º—è —Ä–∞–±–æ—á–µ–π –ø–æ–µ–∑–¥–∫–∏ –ø–æ –°–º–æ–ª–µ–Ω—Å–∫—É –∏ –°–º–æ–ª–µ...
6    –°–µ–≥–æ–¥–Ω—è –í–í–ü –†–æ—Å—Å–∏–∏ –Ω–∞ 17 –ø—Ä–æ—Ü–µ–Ω—Ç–æ–≤ –Ω–∞–ø–æ–ª–Ω—è–µ—Ç—Å...
7    –£—Ñ–∞,4 –¥–µ–∫–∞–±—Ä—è 2019, 16:15 ‚ÄîREGNUM–ë–æ–ª–µ–µ 21 –º–ª—Ä...
8    –ú–ò–ù–ï–†–ê–õ–¨–ù–´–ï –í–û–î–´ /–°—Ç–∞–≤—Ä–æ–ø–æ–ª—å—Å–∫–∏–π –∫—Ä–∞–π/, 4 –¥–µ–∫...
9    04 –¥–µ–∫–∞–±—Ä—è –≤ –±–æ–ª—å—à–æ–º –∑–∞–ª–µ–∞–¥–º–∏–Ω–∏—Å—Ç—Ä–∞—Ü–∏–∏ –°—É–∑—É–Ω—Å...
10   –ö–æ–Ω–∫—É—Ä—Å –Ω–∞ —Ä–µ–∫–æ–Ω—Å—Ç—Ä—É–∫—Ü–∏—é –í–ü–ü-2 –≤ –Ω–æ–≤–æ—Å–∏–±–∏—Ä—Å–∫–æ...
11   –ù–∞–∑–≤–∞–Ω–∏–µ –∫–æ–º–ø–∞–Ω–∏–∏: –ù–µ–ø—É–±–ª–∏—á–Ω–æ–µ –∞–∫—Ü–∏–æ–Ω–µ—Ä–Ω–æ–µ–æ–±—â...
12   –ú–û–°–ö–í–ê, 4 –¥–µ–∫ - –†–ò–ê –ù–æ–≤–æ—Å—Ç–∏/–ü—Ä–∞–π–º.–†–æ—Å—Å–∏–π—Å–∫–∏–π ...
13   –ú–û–°–ö–í–ê, 4 –¥–µ–∫–∞–±—Ä—è./–¢–ê–°–°/.–¢–æ–ø–ª–∏–≤–Ω–∞—è –∫–æ–º–ø–∞–Ω–∏—è–†–æ...
14   –í —ç—Ç–æ–º –≥–æ–¥—É –≤ –ö–∞–ª—Ç–∞—Å–∏–Ω—Å–∫–æ–º —Ä–∞–π–æ–Ω–µ –∞–≥—Ä–æ—Ö–æ–ª–¥–∏–Ω–≥...
15   –°–æ—Ñ–∏—è,4 –¥–µ–∫–∞–±—Ä—è 2019, 16:13 ‚ÄîREGNUM–ü—Ä–∞–≤–∏—Ç–µ–ª—å—Å...
16   –¥–∞—Ç–∞: on –∏—Å—Ç–æ—á–Ω–∏–∫:–£–ø—Ä–∞–≤–ª–µ–Ω–∏–µ –ø–æ —Å–≤—è–∑—è–º —Å –æ–±—â–µ...
17   –ù–£–†-–°–£–õ–¢–ê–ù.–ö–ê–ó–ò–ù–§–û–†–ú‚Äì –î–µ–ø—É—Ç–∞—Ç—ã–°–µ–Ω–∞—Ç–∞–ü–∞—Ä–ª–∞–º–µ–Ω—Ç...
18   Samsung Heavy Industries–ø–æ—Å—Ç–∞–≤–∏—Ç –≤–µ—Ä—Ñ–∏ "–ó–≤–µ–∑–¥...
19   –í –∞–¥–º–∏–Ω–∏—Å—Ç—Ä–∞—Ü–∏–∏ –ö—Ä–∞—Å–Ω–æ–¥–∞—Ä—Å–∫–æ–≥–æ –∫—Ä–∞—è –ø–æ–¥–≤–µ–ª–∏ –ø...

3. –ü—Ä–æ—Å—Ç–∞–≤—å—Ç–µ —Ñ–ª–∞–≥ –≤ –∫–æ–ª–æ–Ω–∫—É source_ria –µ—Å–ª–∏ —Ç–µ–∫—Å—Ç –Ω–æ–≤–æ—Å—Ç–∏ —Å–æ–¥–µ—Ä–∂–∏—Ç: —Ä–∏–∞ –Ω–æ–≤–æ—Å—Ç–∏, —Ç–∞—Å—Å, –∫–æ–º–º–µ—Ä—Å–∞–Ω—Ç. –ü–µ—Ä–µ–¥ –ø–æ–∏—Å–∫–æ–º –ø–µ—Ä–µ–≤–µ–¥–∏—Ç–µ —Ç–µ–∫—Å—Ç—ã –≤ lower –∏ —É–¥–∞–ª–∏—Ç–µ –≤—Å–µ –∫—Ä–æ–º–µ –±—É–∫–≤. –î–∞–Ω–Ω—ã–µ –ø–æ—Å–ª–µ —á–∏—Å—Ç–∫–∏ –∏–∑ –ø—Ä–µ–¥—ã–¥—É—à–µ–≥–æ –∑–∞–¥–∞–Ω–∏—è (‚òÖ‚òÖ‚òÖ)

(hint: df.column.str())

In [493]:
new_df = new_df['text'].str.lower()
new_df

0      —Å–æ–æ–±—â–µ–Ω–∏–µ –æ —Å—É—â–µ—Å—Ç–≤–µ–Ω–Ω–æ–º —Ñ–∞–∫—Ç–µ–æ –≤—ã–ø–ª–∞—á–µ–Ω–Ω—ã—Ö –¥...
1      –Ω–∏–∂–Ω–∏–π–Ω–æ–≤–≥–æ—Ä–æ–¥, 3 –¥–µ–∫–∞–±—Ä—è 2019, 22:41 - regnu...
2      —É–ª—å—è–Ω–æ–≤—Å–∫, 3 –¥–µ–∫–∞–±—Ä—è 2019, 11:38 - regnum –≤—É–ª...
3      —Å–∞–º–∞—Ä—Å–∫–∞—è –æ–±–ª–∞—Å—Ç—å –ø—Ä–∏–∑–Ω–∞–Ω–∞ –æ–¥–Ω–∏–º –∏–∑ –ª–∏–¥–µ—Ä–æ–≤ —Ä...
4      –æ–∫—Ä—É–∂–Ω–∞—è –∞–¥–º–∏–Ω–∏—Å—Ç—Ä–∞—Ü–∏—è —è–∫—É—Ç—Å–∫–∞ –ø–æ–¥–ø–∏—Å–∞–ª–∞ —Å–æ–≥–ª...
5      –≤–æ –≤—Ä–µ–º—è —Ä–∞–±–æ—á–µ–π –ø–æ–µ–∑–¥–∫–∏ –ø–æ —Å–º–æ–ª–µ–Ω—Å–∫—É –∏ —Å–º–æ–ª–µ...
6      —Å–µ–≥–æ–¥–Ω—è –≤–≤–ø —Ä–æ—Å—Å–∏–∏ –Ω–∞ 17 –ø—Ä–æ—Ü–µ–Ω—Ç–æ–≤ –Ω–∞–ø–æ–ª–Ω—è–µ—Ç—Å...
7      —É—Ñ–∞,4 –¥–µ–∫–∞–±—Ä—è 2019, 16:15 ‚Äîregnum–±–æ–ª–µ–µ 21 –º–ª—Ä...
8      –º–∏–Ω–µ—Ä–∞–ª—å–Ω—ã–µ –≤–æ–¥—ã /—Å—Ç–∞–≤—Ä–æ–ø–æ–ª—å—Å–∫–∏–π –∫—Ä–∞–π/, 4 –¥–µ–∫...
9      04 –¥–µ–∫–∞–±—Ä—è –≤ –±–æ–ª—å—à–æ–º –∑–∞–ª–µ–∞–¥–º–∏–Ω–∏—Å—Ç—Ä–∞—Ü–∏–∏ —Å—É–∑—É–Ω—Å...
10     –∫–æ–Ω–∫—É—Ä—Å –Ω–∞ —Ä–µ–∫–æ–Ω—Å—Ç—Ä—É–∫—Ü–∏—é –≤–ø–ø-2 –≤ –Ω–æ–≤–æ—Å–∏–±–∏—Ä—Å–∫–æ...
11     –Ω–∞–∑–≤–∞–Ω–∏–µ –∫–æ–º–ø–∞–Ω–∏–∏: –Ω–µ–ø—É–±–ª–∏—á–Ω–æ–µ –∞–∫—Ü–∏–æ–Ω–µ—Ä–Ω–æ–µ–æ–±—â...
12     –º–æ—Å–∫–≤–∞, 4 –¥–µ–∫ - —Ä–∏–∞ –Ω–æ–≤–æ—Å—Ç–∏/–ø—Ä–∞–π–º.—Ä–æ—Å—Å–∏–π—Å–∫–∏–π ...
13     –º–æ—Å–∫–≤–∞, 4 –¥–µ–∫–∞–±—Ä—è./—Ç–∞—Å—Å/.—Ç–æ–ø–ª–∏–≤–Ω–∞—è –∫–æ–º–ø–∞–Ω–∏—è—Ä–æ...
14     –≤ —ç—Ç–æ–º –≥–æ–¥—É –≤ –∫–∞–ª—Ç–∞—Å–∏–Ω—Å–∫–æ–º —Ä–∞–π–æ–Ω–µ –∞–≥—Ä–æ—Ö–æ–ª–¥–∏–Ω–≥...
15     —Å–æ—Ñ–∏—è,4 –¥–µ–∫–∞–±—Ä—è 2019, 16:13 ‚Äîregnum–ø—Ä–∞–≤–∏—Ç–µ–ª—å—Å...
16     –¥–∞—Ç–∞: on –∏—Å—Ç–æ—á–Ω–∏–∫:—É–ø—Ä–∞–≤–ª–µ–Ω–∏–µ –ø–æ —Å–≤—è–∑—è–º —Å –æ–±—â–µ...
17     –Ω—É—Ä-—Å—É–ª—Ç–∞–Ω.–∫–∞–∑–∏–Ω—Ñ–æ—Ä–º‚Äì –¥–µ–ø—É—Ç–∞—Ç—ã—Å–µ–Ω–∞—Ç–∞–ø–∞—Ä–ª–∞–º–µ–Ω—Ç...
18     samsung heavy industries–ø–æ—Å—Ç–∞–≤–∏—Ç –≤–µ—Ä—Ñ–∏ "–∑–≤–µ–∑–¥...
19     –≤ –∞–¥–º–∏–Ω–∏—Å—Ç—Ä–∞—Ü–∏–∏ –∫—Ä–∞—Å–Ω–æ–¥–∞—Ä—Å–∫–æ–≥–æ –∫—Ä–∞—è –ø–æ–¥–≤–µ–ª–∏ –ø...
Name: text, dtype: object

In [514]:
import re

new_df = new_df.str.replace(r'[^a-z–∞-—è ]','').to_frame()

Index(['text'], dtype='object')

In [515]:
new_df['source_ria'] = new_df['text'].str.contains(r'—Ç–∞—Å—Å|—Ä–∏–∞ –Ω–æ–≤–æ—Å—Ç–∏|–∫–æ–º–º–µ—Ä—Å–∞–Ω—Ç')

new_df

                                                 text  source_ria
0    —Å–æ–æ–±—â–µ–Ω–∏–µ –æ —Å—É—â–µ—Å—Ç–≤–µ–Ω–Ω–æ–º —Ñ–∞–∫—Ç–µ–æ –≤—ã–ø–ª–∞—á–µ–Ω–Ω—ã—Ö –¥...       False
1    –Ω–∏–∂–Ω–∏–π–Ω–æ–≤–≥–æ—Ä–æ–¥  –¥–µ–∫–∞–±—Ä—è    regnum –±—ã–≤—à–∏–π –≥–ª–∞–≤...       False
2    —É–ª—å—è–Ω–æ–≤—Å–∫  –¥–µ–∫–∞–±—Ä—è    regnum –≤—É–ª—å—è–Ω–æ–≤—Å–∫–æ–º –∏–Ω–¥...       False
3    —Å–∞–º–∞—Ä—Å–∫–∞—è –æ–±–ª–∞—Å—Ç—å –ø—Ä–∏–∑–Ω–∞–Ω–∞ –æ–¥–Ω–∏–º –∏–∑ –ª–∏–¥–µ—Ä–æ–≤ —Ä...       False
4    –æ–∫—Ä—É–∂–Ω–∞—è –∞–¥–º–∏–Ω–∏—Å—Ç—Ä–∞—Ü–∏—è —è–∫—É—Ç—Å–∫–∞ –ø–æ–¥–ø–∏—Å–∞–ª–∞ —Å–æ–≥–ª...       False
5    –≤–æ –≤—Ä–µ–º—è —Ä–∞–±–æ—á–µ–π –ø–æ–µ–∑–¥–∫–∏ –ø–æ —Å–º–æ–ª–µ–Ω—Å–∫—É –∏ —Å–º–æ–ª–µ...       False
6    —Å–µ–≥–æ–¥–Ω—è –≤–≤–ø —Ä–æ—Å—Å–∏–∏ –Ω–∞  –ø—Ä–æ—Ü–µ–Ω—Ç–æ–≤ –Ω–∞–ø–æ–ª–Ω—è–µ—Ç—Å—è ...       False
7    —É—Ñ–∞ –¥–µ–∫–∞–±—Ä—è   regnum–±–æ–ª–µ–µ  –º–ª—Ä–¥ —Ä—É–±–ª–µ–π –∏–Ω–≤–µ—Å—Ç...       False
8    –º–∏–Ω–µ—Ä–∞–ª—å–Ω—ã–µ –≤–æ–¥—ã —Å—Ç–∞–≤—Ä–æ–ø–æ–ª—å—Å–∫–∏–π –∫—Ä–∞–π  –¥–µ–∫–∞–±—Ä—è...        True
9     –¥–µ–∫–∞–±—Ä—è –≤ –±–æ–ª—å—à–æ–º –∑–∞–ª–µ–∞–¥–º–∏–Ω–∏—Å—Ç—Ä–∞—Ü–∏–∏ —Å—É–∑—É–Ω—Å–∫–æ...       False
10   –∫–æ–Ω–∫—É—Ä—Å –Ω–∞ —Ä–µ–∫–æ–Ω—Å—Ç—Ä—É–∫—Ü–∏—é –≤–ø–ø –≤ –Ω–æ–≤–æ—Å–∏–±–∏—Ä—Å–∫–æ–º ...        True
11   –Ω–∞–∑–≤–∞–Ω–∏–µ –∫–æ–º–ø–∞–Ω–∏–∏ –Ω–µ–ø—É–±–ª–∏—á–Ω–æ–µ –∞–∫—Ü–∏–æ–Ω–µ—Ä–Ω–æ–µ–æ–±—â–µ...       False
12   –º–æ—Å–∫–≤–∞  –¥–µ–∫  —Ä–∏–∞ –Ω–æ–≤–æ—Å—Ç–∏–ø—Ä–∞–π–º—Ä–æ—Å—Å–∏–π—Å–∫–∏–π –ø—Ä–æ–∏–∑...        True
13   –º–æ—Å–∫–≤–∞  –¥–µ–∫–∞–±—Ä—è—Ç–∞—Å—Å—Ç–æ–ø–ª–∏–≤–Ω–∞—è –∫–æ–º–ø–∞–Ω–∏—è—Ä–æ—Å–∞—Ç–æ–º–∞...        True
14   –≤ —ç—Ç–æ–º –≥–æ–¥—É –≤ –∫–∞–ª—Ç–∞—Å–∏–Ω—Å–∫–æ–º —Ä–∞–π–æ–Ω–µ –∞–≥—Ä–æ—Ö–æ–ª–¥–∏–Ω–≥...       False
15   —Å–æ—Ñ–∏—è –¥–µ–∫–∞–±—Ä—è   regnum–ø—Ä–∞–≤–∏—Ç–µ–ª—å—Å—Ç–≤–æ –±–æ–ª–≥–∞—Ä–∏–∏ ...       False
16   –¥–∞—Ç–∞ on –∏—Å—Ç–æ—á–Ω–∏–∫—É–ø—Ä–∞–≤–ª–µ–Ω–∏–µ –ø–æ —Å–≤—è–∑—è–º —Å –æ–±—â–µ—Å—Ç...       False
17   –Ω—É—Ä—Å—É–ª—Ç–∞–Ω–∫–∞–∑–∏–Ω—Ñ–æ—Ä–º –¥–µ–ø—É—Ç–∞—Ç—ã—Å–µ–Ω–∞—Ç–∞–ø–∞—Ä–ª–∞–º–µ–Ω—Ç–∞—Ä–∫...       False
18   samsung heavy industries–ø–æ—Å—Ç–∞–≤–∏—Ç –≤–µ—Ä—Ñ–∏ –∑–≤–µ–∑–¥–∞...        True
19   –≤ –∞–¥–º–∏–Ω–∏—Å—Ç—Ä–∞—Ü–∏–∏ –∫—Ä–∞—Å–Ω–æ–¥–∞—Ä—Å–∫–æ–≥–æ –∫—Ä–∞—è –ø–æ–¥–≤–µ–ª–∏ –ø...       False

4. –û—Ç—Ñ–∏–ª—å—Ç—Ä—É–π—Ç–µ —Å—Ç—Ä–æ–∫–∏ —Å –≤–∞–ª–∏–¥–Ω—ã–º–∏ –µ–º–µ–π–ª–∞–º–∏ (‚òÖ‚òÖ‚òÖ)

In [72]:
emails = pd.Series(['buying books at amazom.com', 'rameses@egypt.com', 
                    'matt@t.co', 'narendra@modi.com', 'kek lol@mail.ru'])

reg = emails.str.extract(r'(^[\S]+@[a-z]+\.[\S]+)', expand = False)

emails[~pd.isna(reg)]

1    rameses@egypt.com
2            matt@t.co
3    narendra@modi.com
dtype: object

<img src="gifs/cheers.gif" width="400">